package com.dasannetworks.tms.sb.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.GroupedModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Device service. Represents a row in the &quot;tms_Device&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.dasannetworks.tms.sb.model.impl.DeviceModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.dasannetworks.tms.sb.model.impl.DeviceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Device
 * @see com.dasannetworks.tms.sb.model.impl.DeviceImpl
 * @see com.dasannetworks.tms.sb.model.impl.DeviceModelImpl
 * @generated
 */
public interface DeviceModel extends BaseModel<Device>, GroupedModel {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this interface directly. All methods that expect a device model instance should use the {@link Device} interface instead.
     */

    /**
     * Returns the primary key of this device.
     *
     * @return the primary key of this device
     */
    public long getPrimaryKey();

    /**
     * Sets the primary key of this device.
     *
     * @param primaryKey the primary key of this device
     */
    public void setPrimaryKey(long primaryKey);

    /**
     * Returns the device ID of this device.
     *
     * @return the device ID of this device
     */
    public long getDeviceId();

    /**
     * Sets the device ID of this device.
     *
     * @param deviceId the device ID of this device
     */
    public void setDeviceId(long deviceId);

    /**
     * Returns the group ID of this device.
     *
     * @return the group ID of this device
     */
    @Override
    public long getGroupId();

    /**
     * Sets the group ID of this device.
     *
     * @param groupId the group ID of this device
     */
    @Override
    public void setGroupId(long groupId);

    /**
     * Returns the company ID of this device.
     *
     * @return the company ID of this device
     */
    @Override
    public long getCompanyId();

    /**
     * Sets the company ID of this device.
     *
     * @param companyId the company ID of this device
     */
    @Override
    public void setCompanyId(long companyId);

    /**
     * Returns the user ID of this device.
     *
     * @return the user ID of this device
     */
    @Override
    public long getUserId();

    /**
     * Sets the user ID of this device.
     *
     * @param userId the user ID of this device
     */
    @Override
    public void setUserId(long userId);

    /**
     * Returns the user uuid of this device.
     *
     * @return the user uuid of this device
     * @throws SystemException if a system exception occurred
     */
    @Override
    public String getUserUuid() throws SystemException;

    /**
     * Sets the user uuid of this device.
     *
     * @param userUuid the user uuid of this device
     */
    @Override
    public void setUserUuid(String userUuid);

    /**
     * Returns the user name of this device.
     *
     * @return the user name of this device
     */
    @AutoEscape
    @Override
    public String getUserName();

    /**
     * Sets the user name of this device.
     *
     * @param userName the user name of this device
     */
    @Override
    public void setUserName(String userName);

    /**
     * Returns the create date of this device.
     *
     * @return the create date of this device
     */
    @Override
    public Date getCreateDate();

    /**
     * Sets the create date of this device.
     *
     * @param createDate the create date of this device
     */
    @Override
    public void setCreateDate(Date createDate);

    /**
     * Returns the modified date of this device.
     *
     * @return the modified date of this device
     */
    @Override
    public Date getModifiedDate();

    /**
     * Sets the modified date of this device.
     *
     * @param modifiedDate the modified date of this device
     */
    @Override
    public void setModifiedDate(Date modifiedDate);

    /**
     * Returns the modelname of this device.
     *
     * @return the modelname of this device
     */
    @AutoEscape
    public String getModelname();

    /**
     * Sets the modelname of this device.
     *
     * @param modelname the modelname of this device
     */
    public void setModelname(String modelname);

    /**
     * Returns the serial number of this device.
     *
     * @return the serial number of this device
     */
    @AutoEscape
    public String getSerialNumber();

    /**
     * Sets the serial number of this device.
     *
     * @param serialNumber the serial number of this device
     */
    public void setSerialNumber(String serialNumber);

    /**
     * Returns the hardware revision of this device.
     *
     * @return the hardware revision of this device
     */
    @AutoEscape
    public String getHardwareRevision();

    /**
     * Sets the hardware revision of this device.
     *
     * @param hardwareRevision the hardware revision of this device
     */
    public void setHardwareRevision(String hardwareRevision);

    /**
     * Returns the software revision of this device.
     *
     * @return the software revision of this device
     */
    @AutoEscape
    public String getSoftwareRevision();

    /**
     * Sets the software revision of this device.
     *
     * @param softwareRevision the software revision of this device
     */
    public void setSoftwareRevision(String softwareRevision);

    /**
     * Returns the manufacture serial of this device.
     *
     * @return the manufacture serial of this device
     */
    @AutoEscape
    public String getManufactureSerial();

    /**
     * Sets the manufacture serial of this device.
     *
     * @param manufactureSerial the manufacture serial of this device
     */
    public void setManufactureSerial(String manufactureSerial);

    /**
     * Returns the mac address of this device.
     *
     * @return the mac address of this device
     */
    @AutoEscape
    public String getMacAddress();

    /**
     * Sets the mac address of this device.
     *
     * @param macAddress the mac address of this device
     */
    public void setMacAddress(String macAddress);

    /**
     * Returns the part number of this device.
     *
     * @return the part number of this device
     */
    @AutoEscape
    public String getPartNumber();

    /**
     * Sets the part number of this device.
     *
     * @param partNumber the part number of this device
     */
    public void setPartNumber(String partNumber);

    /**
     * Returns the specification of this device.
     *
     * @return the specification of this device
     */
    @AutoEscape
    public String getSpecification();

    /**
     * Sets the specification of this device.
     *
     * @param specification the specification of this device
     */
    public void setSpecification(String specification);

    /**
     * Returns the factory out of this device.
     *
     * @return the factory out of this device
     */
    public Date getFactoryOut();

    /**
     * Sets the factory out of this device.
     *
     * @param factoryOut the factory out of this device
     */
    public void setFactoryOut(Date factoryOut);

    /**
     * Returns the upload file ID of this device.
     *
     * @return the upload file ID of this device
     */
    public long getUploadFileId();

    /**
     * Sets the upload file ID of this device.
     *
     * @param uploadFileId the upload file ID of this device
     */
    public void setUploadFileId(long uploadFileId);

    @Override
    public boolean isNew();

    @Override
    public void setNew(boolean n);

    @Override
    public boolean isCachedModel();

    @Override
    public void setCachedModel(boolean cachedModel);

    @Override
    public boolean isEscapedModel();

    @Override
    public Serializable getPrimaryKeyObj();

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj);

    @Override
    public ExpandoBridge getExpandoBridge();

    @Override
    public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

    @Override
    public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    @Override
    public Object clone();

    @Override
    public int compareTo(com.dasannetworks.tms.sb.model.Device device);

    @Override
    public int hashCode();

    @Override
    public CacheModel<com.dasannetworks.tms.sb.model.Device> toCacheModel();

    @Override
    public com.dasannetworks.tms.sb.model.Device toEscapedModel();

    @Override
    public com.dasannetworks.tms.sb.model.Device toUnescapedModel();

    @Override
    public String toString();

    @Override
    public String toXmlString();
}
