package com.dasannetworks.vn.sb.model.impl;

import com.dasannetworks.vn.sb.model.DeviceHis;
import com.dasannetworks.vn.sb.service.DeviceHisLocalServiceUtil;

import com.liferay.portal.kernel.exception.SystemException;

/**
 * The extended model base implementation for the DeviceHis service. Represents a row in the &quot;tms_DeviceHis&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link DeviceHisImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see DeviceHisImpl
 * @see com.dasannetworks.vn.sb.model.DeviceHis
 * @generated
 */
public abstract class DeviceHisBaseImpl extends DeviceHisModelImpl
    implements DeviceHis {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a device his model instance should use the {@link DeviceHis} interface instead.
     */
    @Override
    public void persist() throws SystemException {
        if (this.isNew()) {
            DeviceHisLocalServiceUtil.addDeviceHis(this);
        } else {
            DeviceHisLocalServiceUtil.updateDeviceHis(this);
        }
    }
}
