package com.dasannetworks.vn.sb.model.impl;

import com.dasannetworks.vn.sb.model.Partner;
import com.dasannetworks.vn.sb.model.PartnerModel;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;
import com.liferay.portal.util.PortalUtil;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import java.io.Serializable;

import java.sql.Types;

import java.util.Date;
import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the Partner service. Represents a row in the &quot;tms_Partner&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.dasannetworks.vn.sb.model.PartnerModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link PartnerImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see PartnerImpl
 * @see com.dasannetworks.vn.sb.model.Partner
 * @see com.dasannetworks.vn.sb.model.PartnerModel
 * @generated
 */
public class PartnerModelImpl extends BaseModelImpl<Partner>
    implements PartnerModel {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a partner model instance should use the {@link com.dasannetworks.vn.sb.model.Partner} interface instead.
     */
    public static final String TABLE_NAME = "tms_Partner";
    public static final Object[][] TABLE_COLUMNS = {
            { "partnerId", Types.BIGINT },
            { "companyId", Types.BIGINT },
            { "userId", Types.BIGINT },
            { "userName", Types.VARCHAR },
            { "createDate", Types.TIMESTAMP },
            { "modifiedDate", Types.TIMESTAMP },
            { "partnerCode", Types.VARCHAR },
            { "partnerName", Types.VARCHAR },
            { "inCharge", Types.VARCHAR },
            { "email", Types.VARCHAR },
            { "phone", Types.VARCHAR },
            { "address", Types.VARCHAR }
        };
    public static final String TABLE_SQL_CREATE = "create table tms_Partner (partnerId LONG not null primary key,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,partnerCode VARCHAR(75) null,partnerName VARCHAR(75) null,inCharge VARCHAR(75) null,email VARCHAR(75) null,phone VARCHAR(75) null,address VARCHAR(75) null)";
    public static final String TABLE_SQL_DROP = "drop table tms_Partner";
    public static final String ORDER_BY_JPQL = " ORDER BY partner.partnerId ASC";
    public static final String ORDER_BY_SQL = " ORDER BY tms_Partner.partnerId ASC";
    public static final String DATA_SOURCE = "liferayDataSource";
    public static final String SESSION_FACTORY = "liferaySessionFactory";
    public static final String TX_MANAGER = "liferayTransactionManager";
    public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
                "value.object.entity.cache.enabled.com.dasannetworks.vn.sb.model.Partner"),
            false);
    public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
                "value.object.finder.cache.enabled.com.dasannetworks.vn.sb.model.Partner"),
            false);
    public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
                "value.object.column.bitmask.enabled.com.dasannetworks.vn.sb.model.Partner"),
            true);
    public static long PARTNERCODE_COLUMN_BITMASK = 1L;
    public static long PARTNERID_COLUMN_BITMASK = 2L;
    public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
                "lock.expiration.time.com.dasannetworks.vn.sb.model.Partner"));
    private static ClassLoader _classLoader = Partner.class.getClassLoader();
    private static Class<?>[] _escapedModelInterfaces = new Class[] {
            Partner.class
        };
    private long _partnerId;
    private long _companyId;
    private long _userId;
    private String _userUuid;
    private String _userName;
    private Date _createDate;
    private Date _modifiedDate;
    private String _partnerCode;
    private String _originalPartnerCode;
    private String _partnerName;
    private String _inCharge;
    private String _email;
    private String _phone;
    private String _address;
    private long _columnBitmask;
    private Partner _escapedModel;

    public PartnerModelImpl() {
    }

    @Override
    public long getPrimaryKey() {
        return _partnerId;
    }

    @Override
    public void setPrimaryKey(long primaryKey) {
        setPartnerId(primaryKey);
    }

    @Override
    public Serializable getPrimaryKeyObj() {
        return _partnerId;
    }

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj) {
        setPrimaryKey(((Long) primaryKeyObj).longValue());
    }

    @Override
    public Class<?> getModelClass() {
        return Partner.class;
    }

    @Override
    public String getModelClassName() {
        return Partner.class.getName();
    }

    @Override
    public Map<String, Object> getModelAttributes() {
        Map<String, Object> attributes = new HashMap<String, Object>();

        attributes.put("partnerId", getPartnerId());
        attributes.put("companyId", getCompanyId());
        attributes.put("userId", getUserId());
        attributes.put("userName", getUserName());
        attributes.put("createDate", getCreateDate());
        attributes.put("modifiedDate", getModifiedDate());
        attributes.put("partnerCode", getPartnerCode());
        attributes.put("partnerName", getPartnerName());
        attributes.put("inCharge", getInCharge());
        attributes.put("email", getEmail());
        attributes.put("phone", getPhone());
        attributes.put("address", getAddress());

        return attributes;
    }

    @Override
    public void setModelAttributes(Map<String, Object> attributes) {
        Long partnerId = (Long) attributes.get("partnerId");

        if (partnerId != null) {
            setPartnerId(partnerId);
        }

        Long companyId = (Long) attributes.get("companyId");

        if (companyId != null) {
            setCompanyId(companyId);
        }

        Long userId = (Long) attributes.get("userId");

        if (userId != null) {
            setUserId(userId);
        }

        String userName = (String) attributes.get("userName");

        if (userName != null) {
            setUserName(userName);
        }

        Date createDate = (Date) attributes.get("createDate");

        if (createDate != null) {
            setCreateDate(createDate);
        }

        Date modifiedDate = (Date) attributes.get("modifiedDate");

        if (modifiedDate != null) {
            setModifiedDate(modifiedDate);
        }

        String partnerCode = (String) attributes.get("partnerCode");

        if (partnerCode != null) {
            setPartnerCode(partnerCode);
        }

        String partnerName = (String) attributes.get("partnerName");

        if (partnerName != null) {
            setPartnerName(partnerName);
        }

        String inCharge = (String) attributes.get("inCharge");

        if (inCharge != null) {
            setInCharge(inCharge);
        }

        String email = (String) attributes.get("email");

        if (email != null) {
            setEmail(email);
        }

        String phone = (String) attributes.get("phone");

        if (phone != null) {
            setPhone(phone);
        }

        String address = (String) attributes.get("address");

        if (address != null) {
            setAddress(address);
        }
    }

    @Override
    public long getPartnerId() {
        return _partnerId;
    }

    @Override
    public void setPartnerId(long partnerId) {
        _partnerId = partnerId;
    }

    @Override
    public long getCompanyId() {
        return _companyId;
    }

    @Override
    public void setCompanyId(long companyId) {
        _companyId = companyId;
    }

    @Override
    public long getUserId() {
        return _userId;
    }

    @Override
    public void setUserId(long userId) {
        _userId = userId;
    }

    @Override
    public String getUserUuid() throws SystemException {
        return PortalUtil.getUserValue(getUserId(), "uuid", _userUuid);
    }

    @Override
    public void setUserUuid(String userUuid) {
        _userUuid = userUuid;
    }

    @Override
    public String getUserName() {
        if (_userName == null) {
            return StringPool.BLANK;
        } else {
            return _userName;
        }
    }

    @Override
    public void setUserName(String userName) {
        _userName = userName;
    }

    @Override
    public Date getCreateDate() {
        return _createDate;
    }

    @Override
    public void setCreateDate(Date createDate) {
        _createDate = createDate;
    }

    @Override
    public Date getModifiedDate() {
        return _modifiedDate;
    }

    @Override
    public void setModifiedDate(Date modifiedDate) {
        _modifiedDate = modifiedDate;
    }

    @Override
    public String getPartnerCode() {
        if (_partnerCode == null) {
            return StringPool.BLANK;
        } else {
            return _partnerCode;
        }
    }

    @Override
    public void setPartnerCode(String partnerCode) {
        _columnBitmask |= PARTNERCODE_COLUMN_BITMASK;

        if (_originalPartnerCode == null) {
            _originalPartnerCode = _partnerCode;
        }

        _partnerCode = partnerCode;
    }

    public String getOriginalPartnerCode() {
        return GetterUtil.getString(_originalPartnerCode);
    }

    @Override
    public String getPartnerName() {
        if (_partnerName == null) {
            return StringPool.BLANK;
        } else {
            return _partnerName;
        }
    }

    @Override
    public void setPartnerName(String partnerName) {
        _partnerName = partnerName;
    }

    @Override
    public String getInCharge() {
        if (_inCharge == null) {
            return StringPool.BLANK;
        } else {
            return _inCharge;
        }
    }

    @Override
    public void setInCharge(String inCharge) {
        _inCharge = inCharge;
    }

    @Override
    public String getEmail() {
        if (_email == null) {
            return StringPool.BLANK;
        } else {
            return _email;
        }
    }

    @Override
    public void setEmail(String email) {
        _email = email;
    }

    @Override
    public String getPhone() {
        if (_phone == null) {
            return StringPool.BLANK;
        } else {
            return _phone;
        }
    }

    @Override
    public void setPhone(String phone) {
        _phone = phone;
    }

    @Override
    public String getAddress() {
        if (_address == null) {
            return StringPool.BLANK;
        } else {
            return _address;
        }
    }

    @Override
    public void setAddress(String address) {
        _address = address;
    }

    public long getColumnBitmask() {
        return _columnBitmask;
    }

    @Override
    public ExpandoBridge getExpandoBridge() {
        return ExpandoBridgeFactoryUtil.getExpandoBridge(getCompanyId(),
            Partner.class.getName(), getPrimaryKey());
    }

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
        ExpandoBridge expandoBridge = getExpandoBridge();

        expandoBridge.setAttributes(serviceContext);
    }

    @Override
    public Partner toEscapedModel() {
        if (_escapedModel == null) {
            _escapedModel = (Partner) ProxyUtil.newProxyInstance(_classLoader,
                    _escapedModelInterfaces, new AutoEscapeBeanHandler(this));
        }

        return _escapedModel;
    }

    @Override
    public Object clone() {
        PartnerImpl partnerImpl = new PartnerImpl();

        partnerImpl.setPartnerId(getPartnerId());
        partnerImpl.setCompanyId(getCompanyId());
        partnerImpl.setUserId(getUserId());
        partnerImpl.setUserName(getUserName());
        partnerImpl.setCreateDate(getCreateDate());
        partnerImpl.setModifiedDate(getModifiedDate());
        partnerImpl.setPartnerCode(getPartnerCode());
        partnerImpl.setPartnerName(getPartnerName());
        partnerImpl.setInCharge(getInCharge());
        partnerImpl.setEmail(getEmail());
        partnerImpl.setPhone(getPhone());
        partnerImpl.setAddress(getAddress());

        partnerImpl.resetOriginalValues();

        return partnerImpl;
    }

    @Override
    public int compareTo(Partner partner) {
        long primaryKey = partner.getPrimaryKey();

        if (getPrimaryKey() < primaryKey) {
            return -1;
        } else if (getPrimaryKey() > primaryKey) {
            return 1;
        } else {
            return 0;
        }
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }

        if (!(obj instanceof Partner)) {
            return false;
        }

        Partner partner = (Partner) obj;

        long primaryKey = partner.getPrimaryKey();

        if (getPrimaryKey() == primaryKey) {
            return true;
        } else {
            return false;
        }
    }

    @Override
    public int hashCode() {
        return (int) getPrimaryKey();
    }

    @Override
    public void resetOriginalValues() {
        PartnerModelImpl partnerModelImpl = this;

        partnerModelImpl._originalPartnerCode = partnerModelImpl._partnerCode;

        partnerModelImpl._columnBitmask = 0;
    }

    @Override
    public CacheModel<Partner> toCacheModel() {
        PartnerCacheModel partnerCacheModel = new PartnerCacheModel();

        partnerCacheModel.partnerId = getPartnerId();

        partnerCacheModel.companyId = getCompanyId();

        partnerCacheModel.userId = getUserId();

        partnerCacheModel.userName = getUserName();

        String userName = partnerCacheModel.userName;

        if ((userName != null) && (userName.length() == 0)) {
            partnerCacheModel.userName = null;
        }

        Date createDate = getCreateDate();

        if (createDate != null) {
            partnerCacheModel.createDate = createDate.getTime();
        } else {
            partnerCacheModel.createDate = Long.MIN_VALUE;
        }

        Date modifiedDate = getModifiedDate();

        if (modifiedDate != null) {
            partnerCacheModel.modifiedDate = modifiedDate.getTime();
        } else {
            partnerCacheModel.modifiedDate = Long.MIN_VALUE;
        }

        partnerCacheModel.partnerCode = getPartnerCode();

        String partnerCode = partnerCacheModel.partnerCode;

        if ((partnerCode != null) && (partnerCode.length() == 0)) {
            partnerCacheModel.partnerCode = null;
        }

        partnerCacheModel.partnerName = getPartnerName();

        String partnerName = partnerCacheModel.partnerName;

        if ((partnerName != null) && (partnerName.length() == 0)) {
            partnerCacheModel.partnerName = null;
        }

        partnerCacheModel.inCharge = getInCharge();

        String inCharge = partnerCacheModel.inCharge;

        if ((inCharge != null) && (inCharge.length() == 0)) {
            partnerCacheModel.inCharge = null;
        }

        partnerCacheModel.email = getEmail();

        String email = partnerCacheModel.email;

        if ((email != null) && (email.length() == 0)) {
            partnerCacheModel.email = null;
        }

        partnerCacheModel.phone = getPhone();

        String phone = partnerCacheModel.phone;

        if ((phone != null) && (phone.length() == 0)) {
            partnerCacheModel.phone = null;
        }

        partnerCacheModel.address = getAddress();

        String address = partnerCacheModel.address;

        if ((address != null) && (address.length() == 0)) {
            partnerCacheModel.address = null;
        }

        return partnerCacheModel;
    }

    @Override
    public String toString() {
        StringBundler sb = new StringBundler(25);

        sb.append("{partnerId=");
        sb.append(getPartnerId());
        sb.append(", companyId=");
        sb.append(getCompanyId());
        sb.append(", userId=");
        sb.append(getUserId());
        sb.append(", userName=");
        sb.append(getUserName());
        sb.append(", createDate=");
        sb.append(getCreateDate());
        sb.append(", modifiedDate=");
        sb.append(getModifiedDate());
        sb.append(", partnerCode=");
        sb.append(getPartnerCode());
        sb.append(", partnerName=");
        sb.append(getPartnerName());
        sb.append(", inCharge=");
        sb.append(getInCharge());
        sb.append(", email=");
        sb.append(getEmail());
        sb.append(", phone=");
        sb.append(getPhone());
        sb.append(", address=");
        sb.append(getAddress());
        sb.append("}");

        return sb.toString();
    }

    @Override
    public String toXmlString() {
        StringBundler sb = new StringBundler(40);

        sb.append("<model><model-name>");
        sb.append("com.dasannetworks.vn.sb.model.Partner");
        sb.append("</model-name>");

        sb.append(
            "<column><column-name>partnerId</column-name><column-value><![CDATA[");
        sb.append(getPartnerId());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>companyId</column-name><column-value><![CDATA[");
        sb.append(getCompanyId());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>userId</column-name><column-value><![CDATA[");
        sb.append(getUserId());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>userName</column-name><column-value><![CDATA[");
        sb.append(getUserName());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>createDate</column-name><column-value><![CDATA[");
        sb.append(getCreateDate());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>modifiedDate</column-name><column-value><![CDATA[");
        sb.append(getModifiedDate());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>partnerCode</column-name><column-value><![CDATA[");
        sb.append(getPartnerCode());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>partnerName</column-name><column-value><![CDATA[");
        sb.append(getPartnerName());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>inCharge</column-name><column-value><![CDATA[");
        sb.append(getInCharge());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>email</column-name><column-value><![CDATA[");
        sb.append(getEmail());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>phone</column-name><column-value><![CDATA[");
        sb.append(getPhone());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>address</column-name><column-value><![CDATA[");
        sb.append(getAddress());
        sb.append("]]></column-value></column>");

        sb.append("</model>");

        return sb.toString();
    }
}
