package com.dasannetworks.vn.sb.model.impl;

import com.dasannetworks.vn.sb.model.Partner;
import com.dasannetworks.vn.sb.service.PartnerLocalServiceUtil;

import com.liferay.portal.kernel.exception.SystemException;

/**
 * The extended model base implementation for the Partner service. Represents a row in the &quot;tms_Partner&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link PartnerImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see PartnerImpl
 * @see com.dasannetworks.vn.sb.model.Partner
 * @generated
 */
public abstract class PartnerBaseImpl extends PartnerModelImpl
    implements Partner {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a partner model instance should use the {@link Partner} interface instead.
     */
    @Override
    public void persist() throws SystemException {
        if (this.isNew()) {
            PartnerLocalServiceUtil.addPartner(this);
        } else {
            PartnerLocalServiceUtil.updatePartner(this);
        }
    }
}
