package com.dasannetworks.vn.sb.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.AuditedModel;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the DeviceExtOrder service. Represents a row in the &quot;tms_DeviceExtOrder&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.dasannetworks.vn.sb.model.impl.DeviceExtOrderModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.dasannetworks.vn.sb.model.impl.DeviceExtOrderImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see DeviceExtOrder
 * @see com.dasannetworks.vn.sb.model.impl.DeviceExtOrderImpl
 * @see com.dasannetworks.vn.sb.model.impl.DeviceExtOrderModelImpl
 * @generated
 */
public interface DeviceExtOrderModel extends AuditedModel,
    BaseModel<DeviceExtOrder> {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this interface directly. All methods that expect a device ext order model instance should use the {@link DeviceExtOrder} interface instead.
     */

    /**
     * Returns the primary key of this device ext order.
     *
     * @return the primary key of this device ext order
     */
    public long getPrimaryKey();

    /**
     * Sets the primary key of this device ext order.
     *
     * @param primaryKey the primary key of this device ext order
     */
    public void setPrimaryKey(long primaryKey);

    /**
     * Returns the device ext order ID of this device ext order.
     *
     * @return the device ext order ID of this device ext order
     */
    public long getDeviceExtOrderId();

    /**
     * Sets the device ext order ID of this device ext order.
     *
     * @param deviceExtOrderId the device ext order ID of this device ext order
     */
    public void setDeviceExtOrderId(long deviceExtOrderId);

    /**
     * Returns the company ID of this device ext order.
     *
     * @return the company ID of this device ext order
     */
    @Override
    public long getCompanyId();

    /**
     * Sets the company ID of this device ext order.
     *
     * @param companyId the company ID of this device ext order
     */
    @Override
    public void setCompanyId(long companyId);

    /**
     * Returns the user ID of this device ext order.
     *
     * @return the user ID of this device ext order
     */
    @Override
    public long getUserId();

    /**
     * Sets the user ID of this device ext order.
     *
     * @param userId the user ID of this device ext order
     */
    @Override
    public void setUserId(long userId);

    /**
     * Returns the user uuid of this device ext order.
     *
     * @return the user uuid of this device ext order
     * @throws SystemException if a system exception occurred
     */
    @Override
    public String getUserUuid() throws SystemException;

    /**
     * Sets the user uuid of this device ext order.
     *
     * @param userUuid the user uuid of this device ext order
     */
    @Override
    public void setUserUuid(String userUuid);

    /**
     * Returns the user name of this device ext order.
     *
     * @return the user name of this device ext order
     */
    @AutoEscape
    @Override
    public String getUserName();

    /**
     * Sets the user name of this device ext order.
     *
     * @param userName the user name of this device ext order
     */
    @Override
    public void setUserName(String userName);

    /**
     * Returns the create date of this device ext order.
     *
     * @return the create date of this device ext order
     */
    @Override
    public Date getCreateDate();

    /**
     * Sets the create date of this device ext order.
     *
     * @param createDate the create date of this device ext order
     */
    @Override
    public void setCreateDate(Date createDate);

    /**
     * Returns the modified date of this device ext order.
     *
     * @return the modified date of this device ext order
     */
    @Override
    public Date getModifiedDate();

    /**
     * Sets the modified date of this device ext order.
     *
     * @param modifiedDate the modified date of this device ext order
     */
    @Override
    public void setModifiedDate(Date modifiedDate);

    /**
     * Returns the device ext order number of this device ext order.
     *
     * @return the device ext order number of this device ext order
     */
    @AutoEscape
    public String getDeviceExtOrderNumber();

    /**
     * Sets the device ext order number of this device ext order.
     *
     * @param deviceExtOrderNumber the device ext order number of this device ext order
     */
    public void setDeviceExtOrderNumber(String deviceExtOrderNumber);

    /**
     * Returns the note of this device ext order.
     *
     * @return the note of this device ext order
     */
    @AutoEscape
    public String getNote();

    /**
     * Sets the note of this device ext order.
     *
     * @param note the note of this device ext order
     */
    public void setNote(String note);

    @Override
    public boolean isNew();

    @Override
    public void setNew(boolean n);

    @Override
    public boolean isCachedModel();

    @Override
    public void setCachedModel(boolean cachedModel);

    @Override
    public boolean isEscapedModel();

    @Override
    public Serializable getPrimaryKeyObj();

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj);

    @Override
    public ExpandoBridge getExpandoBridge();

    @Override
    public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

    @Override
    public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    @Override
    public Object clone();

    @Override
    public int compareTo(
        com.dasannetworks.vn.sb.model.DeviceExtOrder deviceExtOrder);

    @Override
    public int hashCode();

    @Override
    public CacheModel<com.dasannetworks.vn.sb.model.DeviceExtOrder> toCacheModel();

    @Override
    public com.dasannetworks.vn.sb.model.DeviceExtOrder toEscapedModel();

    @Override
    public com.dasannetworks.vn.sb.model.DeviceExtOrder toUnescapedModel();

    @Override
    public String toString();

    @Override
    public String toXmlString();
}
