package com.dasannetworks.vn.sb.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.AuditedModel;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Partner service. Represents a row in the &quot;tms_Partner&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.dasannetworks.vn.sb.model.impl.PartnerModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.dasannetworks.vn.sb.model.impl.PartnerImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Partner
 * @see com.dasannetworks.vn.sb.model.impl.PartnerImpl
 * @see com.dasannetworks.vn.sb.model.impl.PartnerModelImpl
 * @generated
 */
public interface PartnerModel extends AuditedModel, BaseModel<Partner> {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this interface directly. All methods that expect a partner model instance should use the {@link Partner} interface instead.
     */

    /**
     * Returns the primary key of this partner.
     *
     * @return the primary key of this partner
     */
    public long getPrimaryKey();

    /**
     * Sets the primary key of this partner.
     *
     * @param primaryKey the primary key of this partner
     */
    public void setPrimaryKey(long primaryKey);

    /**
     * Returns the partner ID of this partner.
     *
     * @return the partner ID of this partner
     */
    public long getPartnerId();

    /**
     * Sets the partner ID of this partner.
     *
     * @param partnerId the partner ID of this partner
     */
    public void setPartnerId(long partnerId);

    /**
     * Returns the company ID of this partner.
     *
     * @return the company ID of this partner
     */
    @Override
    public long getCompanyId();

    /**
     * Sets the company ID of this partner.
     *
     * @param companyId the company ID of this partner
     */
    @Override
    public void setCompanyId(long companyId);

    /**
     * Returns the user ID of this partner.
     *
     * @return the user ID of this partner
     */
    @Override
    public long getUserId();

    /**
     * Sets the user ID of this partner.
     *
     * @param userId the user ID of this partner
     */
    @Override
    public void setUserId(long userId);

    /**
     * Returns the user uuid of this partner.
     *
     * @return the user uuid of this partner
     * @throws SystemException if a system exception occurred
     */
    @Override
    public String getUserUuid() throws SystemException;

    /**
     * Sets the user uuid of this partner.
     *
     * @param userUuid the user uuid of this partner
     */
    @Override
    public void setUserUuid(String userUuid);

    /**
     * Returns the user name of this partner.
     *
     * @return the user name of this partner
     */
    @AutoEscape
    @Override
    public String getUserName();

    /**
     * Sets the user name of this partner.
     *
     * @param userName the user name of this partner
     */
    @Override
    public void setUserName(String userName);

    /**
     * Returns the create date of this partner.
     *
     * @return the create date of this partner
     */
    @Override
    public Date getCreateDate();

    /**
     * Sets the create date of this partner.
     *
     * @param createDate the create date of this partner
     */
    @Override
    public void setCreateDate(Date createDate);

    /**
     * Returns the modified date of this partner.
     *
     * @return the modified date of this partner
     */
    @Override
    public Date getModifiedDate();

    /**
     * Sets the modified date of this partner.
     *
     * @param modifiedDate the modified date of this partner
     */
    @Override
    public void setModifiedDate(Date modifiedDate);

    /**
     * Returns the partner code of this partner.
     *
     * @return the partner code of this partner
     */
    @AutoEscape
    public String getPartnerCode();

    /**
     * Sets the partner code of this partner.
     *
     * @param partnerCode the partner code of this partner
     */
    public void setPartnerCode(String partnerCode);

    /**
     * Returns the partner name of this partner.
     *
     * @return the partner name of this partner
     */
    @AutoEscape
    public String getPartnerName();

    /**
     * Sets the partner name of this partner.
     *
     * @param partnerName the partner name of this partner
     */
    public void setPartnerName(String partnerName);

    /**
     * Returns the in charge of this partner.
     *
     * @return the in charge of this partner
     */
    @AutoEscape
    public String getInCharge();

    /**
     * Sets the in charge of this partner.
     *
     * @param inCharge the in charge of this partner
     */
    public void setInCharge(String inCharge);

    /**
     * Returns the email of this partner.
     *
     * @return the email of this partner
     */
    @AutoEscape
    public String getEmail();

    /**
     * Sets the email of this partner.
     *
     * @param email the email of this partner
     */
    public void setEmail(String email);

    /**
     * Returns the phone of this partner.
     *
     * @return the phone of this partner
     */
    @AutoEscape
    public String getPhone();

    /**
     * Sets the phone of this partner.
     *
     * @param phone the phone of this partner
     */
    public void setPhone(String phone);

    /**
     * Returns the address of this partner.
     *
     * @return the address of this partner
     */
    @AutoEscape
    public String getAddress();

    /**
     * Sets the address of this partner.
     *
     * @param address the address of this partner
     */
    public void setAddress(String address);

    @Override
    public boolean isNew();

    @Override
    public void setNew(boolean n);

    @Override
    public boolean isCachedModel();

    @Override
    public void setCachedModel(boolean cachedModel);

    @Override
    public boolean isEscapedModel();

    @Override
    public Serializable getPrimaryKeyObj();

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj);

    @Override
    public ExpandoBridge getExpandoBridge();

    @Override
    public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

    @Override
    public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    @Override
    public Object clone();

    @Override
    public int compareTo(com.dasannetworks.vn.sb.model.Partner partner);

    @Override
    public int hashCode();

    @Override
    public CacheModel<com.dasannetworks.vn.sb.model.Partner> toCacheModel();

    @Override
    public com.dasannetworks.vn.sb.model.Partner toEscapedModel();

    @Override
    public com.dasannetworks.vn.sb.model.Partner toUnescapedModel();

    @Override
    public String toString();

    @Override
    public String toXmlString();
}
