package com.dasannetworks.vn.sb.model;

import com.dasannetworks.vn.sb.service.persistence.RmaRequestDevicePK;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.AuditedModel;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the RmaRequestDevice service. Represents a row in the &quot;tms_RmaRequestDevice&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.dasannetworks.vn.sb.model.impl.RmaRequestDeviceModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.dasannetworks.vn.sb.model.impl.RmaRequestDeviceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see RmaRequestDevice
 * @see com.dasannetworks.vn.sb.model.impl.RmaRequestDeviceImpl
 * @see com.dasannetworks.vn.sb.model.impl.RmaRequestDeviceModelImpl
 * @generated
 */
public interface RmaRequestDeviceModel extends AuditedModel,
    BaseModel<RmaRequestDevice> {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this interface directly. All methods that expect a rma request device model instance should use the {@link RmaRequestDevice} interface instead.
     */

    /**
     * Returns the primary key of this rma request device.
     *
     * @return the primary key of this rma request device
     */
    public RmaRequestDevicePK getPrimaryKey();

    /**
     * Sets the primary key of this rma request device.
     *
     * @param primaryKey the primary key of this rma request device
     */
    public void setPrimaryKey(RmaRequestDevicePK primaryKey);

    /**
     * Returns the rma request ID of this rma request device.
     *
     * @return the rma request ID of this rma request device
     */
    public long getRmaRequestId();

    /**
     * Sets the rma request ID of this rma request device.
     *
     * @param rmaRequestId the rma request ID of this rma request device
     */
    public void setRmaRequestId(long rmaRequestId);

    /**
     * Returns the device ID of this rma request device.
     *
     * @return the device ID of this rma request device
     */
    public long getDeviceId();

    /**
     * Sets the device ID of this rma request device.
     *
     * @param deviceId the device ID of this rma request device
     */
    public void setDeviceId(long deviceId);

    /**
     * Returns the company ID of this rma request device.
     *
     * @return the company ID of this rma request device
     */
    @Override
    public long getCompanyId();

    /**
     * Sets the company ID of this rma request device.
     *
     * @param companyId the company ID of this rma request device
     */
    @Override
    public void setCompanyId(long companyId);

    /**
     * Returns the user ID of this rma request device.
     *
     * @return the user ID of this rma request device
     */
    @Override
    public long getUserId();

    /**
     * Sets the user ID of this rma request device.
     *
     * @param userId the user ID of this rma request device
     */
    @Override
    public void setUserId(long userId);

    /**
     * Returns the user uuid of this rma request device.
     *
     * @return the user uuid of this rma request device
     * @throws SystemException if a system exception occurred
     */
    @Override
    public String getUserUuid() throws SystemException;

    /**
     * Sets the user uuid of this rma request device.
     *
     * @param userUuid the user uuid of this rma request device
     */
    @Override
    public void setUserUuid(String userUuid);

    /**
     * Returns the user name of this rma request device.
     *
     * @return the user name of this rma request device
     */
    @AutoEscape
    @Override
    public String getUserName();

    /**
     * Sets the user name of this rma request device.
     *
     * @param userName the user name of this rma request device
     */
    @Override
    public void setUserName(String userName);

    /**
     * Returns the create date of this rma request device.
     *
     * @return the create date of this rma request device
     */
    @Override
    public Date getCreateDate();

    /**
     * Sets the create date of this rma request device.
     *
     * @param createDate the create date of this rma request device
     */
    @Override
    public void setCreateDate(Date createDate);

    /**
     * Returns the modified date of this rma request device.
     *
     * @return the modified date of this rma request device
     */
    @Override
    public Date getModifiedDate();

    /**
     * Sets the modified date of this rma request device.
     *
     * @param modifiedDate the modified date of this rma request device
     */
    @Override
    public void setModifiedDate(Date modifiedDate);

    /**
     * Returns the original serial number of this rma request device.
     *
     * @return the original serial number of this rma request device
     */
    @AutoEscape
    public String getOriginalSerialNumber();

    /**
     * Sets the original serial number of this rma request device.
     *
     * @param originalSerialNumber the original serial number of this rma request device
     */
    public void setOriginalSerialNumber(String originalSerialNumber);

    /**
     * Returns the faulty date of this rma request device.
     *
     * @return the faulty date of this rma request device
     */
    public Date getFaultyDate();

    /**
     * Sets the faulty date of this rma request device.
     *
     * @param faultyDate the faulty date of this rma request device
     */
    public void setFaultyDate(Date faultyDate);

    /**
     * Returns the faulty note of this rma request device.
     *
     * @return the faulty note of this rma request device
     */
    @AutoEscape
    public String getFaultyNote();

    /**
     * Sets the faulty note of this rma request device.
     *
     * @param faultyNote the faulty note of this rma request device
     */
    public void setFaultyNote(String faultyNote);

    /**
     * Returns the action of this rma request device.
     *
     * @return the action of this rma request device
     */
    @AutoEscape
    public String getAction();

    /**
     * Sets the action of this rma request device.
     *
     * @param action the action of this rma request device
     */
    public void setAction(String action);

    /**
     * Returns the partner ID of this rma request device.
     *
     * @return the partner ID of this rma request device
     */
    public Long getPartnerId();

    /**
     * Sets the partner ID of this rma request device.
     *
     * @param partnerId the partner ID of this rma request device
     */
    public void setPartnerId(Long partnerId);

    /**
     * Returns the partner in charge of this rma request device.
     *
     * @return the partner in charge of this rma request device
     */
    @AutoEscape
    public String getPartnerInCharge();

    /**
     * Sets the partner in charge of this rma request device.
     *
     * @param partnerInCharge the partner in charge of this rma request device
     */
    public void setPartnerInCharge(String partnerInCharge);

    /**
     * Returns the partner email of this rma request device.
     *
     * @return the partner email of this rma request device
     */
    @AutoEscape
    public String getPartnerEmail();

    /**
     * Sets the partner email of this rma request device.
     *
     * @param partnerEmail the partner email of this rma request device
     */
    public void setPartnerEmail(String partnerEmail);

    /**
     * Returns the partner phone of this rma request device.
     *
     * @return the partner phone of this rma request device
     */
    @AutoEscape
    public String getPartnerPhone();

    /**
     * Sets the partner phone of this rma request device.
     *
     * @param partnerPhone the partner phone of this rma request device
     */
    public void setPartnerPhone(String partnerPhone);

    /**
     * Returns the partner address of this rma request device.
     *
     * @return the partner address of this rma request device
     */
    @AutoEscape
    public String getPartnerAddress();

    /**
     * Sets the partner address of this rma request device.
     *
     * @param partnerAddress the partner address of this rma request device
     */
    public void setPartnerAddress(String partnerAddress);

    /**
     * Returns the sending est return date of this rma request device.
     *
     * @return the sending est return date of this rma request device
     */
    public Date getSendingEstReturnDate();

    /**
     * Sets the sending est return date of this rma request device.
     *
     * @param sendingEstReturnDate the sending est return date of this rma request device
     */
    public void setSendingEstReturnDate(Date sendingEstReturnDate);

    /**
     * Returns the sending returned date of this rma request device.
     *
     * @return the sending returned date of this rma request device
     */
    public Date getSendingReturnedDate();

    /**
     * Sets the sending returned date of this rma request device.
     *
     * @param sendingReturnedDate the sending returned date of this rma request device
     */
    public void setSendingReturnedDate(Date sendingReturnedDate);

    /**
     * Returns the sending assigned date of this rma request device.
     *
     * @return the sending assigned date of this rma request device
     */
    public Date getSendingAssignedDate();

    /**
     * Sets the sending assigned date of this rma request device.
     *
     * @param sendingAssignedDate the sending assigned date of this rma request device
     */
    public void setSendingAssignedDate(Date sendingAssignedDate);

    /**
     * Returns the sending note of this rma request device.
     *
     * @return the sending note of this rma request device
     */
    @AutoEscape
    public String getSendingNote();

    /**
     * Sets the sending note of this rma request device.
     *
     * @param sendingNote the sending note of this rma request device
     */
    public void setSendingNote(String sendingNote);

    /**
     * Returns the receiving returned date of this rma request device.
     *
     * @return the receiving returned date of this rma request device
     */
    public Date getReceivingReturnedDate();

    /**
     * Sets the receiving returned date of this rma request device.
     *
     * @param receivingReturnedDate the receiving returned date of this rma request device
     */
    public void setReceivingReturnedDate(Date receivingReturnedDate);

    /**
     * Returns the receiving note of this rma request device.
     *
     * @return the receiving note of this rma request device
     */
    @AutoEscape
    public String getReceivingNote();

    /**
     * Sets the receiving note of this rma request device.
     *
     * @param receivingNote the receiving note of this rma request device
     */
    public void setReceivingNote(String receivingNote);

    /**
     * Returns the returning returned date of this rma request device.
     *
     * @return the returning returned date of this rma request device
     */
    public Date getReturningReturnedDate();

    /**
     * Sets the returning returned date of this rma request device.
     *
     * @param returningReturnedDate the returning returned date of this rma request device
     */
    public void setReturningReturnedDate(Date returningReturnedDate);

    /**
     * Returns the returning note of this rma request device.
     *
     * @return the returning note of this rma request device
     */
    @AutoEscape
    public String getReturningNote();

    /**
     * Sets the returning note of this rma request device.
     *
     * @param returningNote the returning note of this rma request device
     */
    public void setReturningNote(String returningNote);

    /**
     * Returns the duplicated rma request ID of this rma request device.
     *
     * @return the duplicated rma request ID of this rma request device
     */
    public Long getDuplicatedRmaRequestId();

    /**
     * Sets the duplicated rma request ID of this rma request device.
     *
     * @param duplicatedRmaRequestId the duplicated rma request ID of this rma request device
     */
    public void setDuplicatedRmaRequestId(Long duplicatedRmaRequestId);

    /**
     * Returns the denied date of this rma request device.
     *
     * @return the denied date of this rma request device
     */
    public Date getDeniedDate();

    /**
     * Sets the denied date of this rma request device.
     *
     * @param deniedDate the denied date of this rma request device
     */
    public void setDeniedDate(Date deniedDate);

    /**
     * Returns the denied note of this rma request device.
     *
     * @return the denied note of this rma request device
     */
    @AutoEscape
    public String getDeniedNote();

    /**
     * Sets the denied note of this rma request device.
     *
     * @param deniedNote the denied note of this rma request device
     */
    public void setDeniedNote(String deniedNote);

    /**
     * Returns the replaced date of this rma request device.
     *
     * @return the replaced date of this rma request device
     */
    public Date getReplacedDate();

    /**
     * Sets the replaced date of this rma request device.
     *
     * @param replacedDate the replaced date of this rma request device
     */
    public void setReplacedDate(Date replacedDate);

    /**
     * Returns the replaced note of this rma request device.
     *
     * @return the replaced note of this rma request device
     */
    @AutoEscape
    public String getReplacedNote();

    /**
     * Sets the replaced note of this rma request device.
     *
     * @param replacedNote the replaced note of this rma request device
     */
    public void setReplacedNote(String replacedNote);

    /**
     * Returns the replaced number of this rma request device.
     *
     * @return the replaced number of this rma request device
     */
    @AutoEscape
    public String getReplacedNumber();

    /**
     * Sets the replaced number of this rma request device.
     *
     * @param replacedNumber the replaced number of this rma request device
     */
    public void setReplacedNumber(String replacedNumber);

    /**
     * Returns the replaced old device ID of this rma request device.
     *
     * @return the replaced old device ID of this rma request device
     */
    public Long getReplacedOldDeviceId();

    /**
     * Sets the replaced old device ID of this rma request device.
     *
     * @param replacedOldDeviceId the replaced old device ID of this rma request device
     */
    public void setReplacedOldDeviceId(Long replacedOldDeviceId);

    /**
     * Returns the replaced old device ext ID of this rma request device.
     *
     * @return the replaced old device ext ID of this rma request device
     */
    public Long getReplacedOldDeviceExtId();

    /**
     * Sets the replaced old device ext ID of this rma request device.
     *
     * @param replacedOldDeviceExtId the replaced old device ext ID of this rma request device
     */
    public void setReplacedOldDeviceExtId(Long replacedOldDeviceExtId);

    /**
     * Returns the replaced new device ID of this rma request device.
     *
     * @return the replaced new device ID of this rma request device
     */
    public Long getReplacedNewDeviceId();

    /**
     * Sets the replaced new device ID of this rma request device.
     *
     * @param replacedNewDeviceId the replaced new device ID of this rma request device
     */
    public void setReplacedNewDeviceId(Long replacedNewDeviceId);

    /**
     * Returns the replaced new device ext ID of this rma request device.
     *
     * @return the replaced new device ext ID of this rma request device
     */
    public Long getReplacedNewDeviceExtId();

    /**
     * Sets the replaced new device ext ID of this rma request device.
     *
     * @param replacedNewDeviceExtId the replaced new device ext ID of this rma request device
     */
    public void setReplacedNewDeviceExtId(Long replacedNewDeviceExtId);

    /**
     * Returns the old status of this rma request device.
     *
     * @return the old status of this rma request device
     */
    public int getOldStatus();

    /**
     * Sets the old status of this rma request device.
     *
     * @param oldStatus the old status of this rma request device
     */
    public void setOldStatus(int oldStatus);

    /**
     * Returns the status of this rma request device.
     *
     * @return the status of this rma request device
     */
    public int getStatus();

    /**
     * Sets the status of this rma request device.
     *
     * @param status the status of this rma request device
     */
    public void setStatus(int status);

    /**
     * Returns the status by user ID of this rma request device.
     *
     * @return the status by user ID of this rma request device
     */
    public long getStatusByUserId();

    /**
     * Sets the status by user ID of this rma request device.
     *
     * @param statusByUserId the status by user ID of this rma request device
     */
    public void setStatusByUserId(long statusByUserId);

    /**
     * Returns the status by user uuid of this rma request device.
     *
     * @return the status by user uuid of this rma request device
     * @throws SystemException if a system exception occurred
     */
    public String getStatusByUserUuid() throws SystemException;

    /**
     * Sets the status by user uuid of this rma request device.
     *
     * @param statusByUserUuid the status by user uuid of this rma request device
     */
    public void setStatusByUserUuid(String statusByUserUuid);

    /**
     * Returns the status date of this rma request device.
     *
     * @return the status date of this rma request device
     */
    public Date getStatusDate();

    /**
     * Sets the status date of this rma request device.
     *
     * @param statusDate the status date of this rma request device
     */
    public void setStatusDate(Date statusDate);

    @Override
    public boolean isNew();

    @Override
    public void setNew(boolean n);

    @Override
    public boolean isCachedModel();

    @Override
    public void setCachedModel(boolean cachedModel);

    @Override
    public boolean isEscapedModel();

    @Override
    public Serializable getPrimaryKeyObj();

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj);

    @Override
    public ExpandoBridge getExpandoBridge();

    @Override
    public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

    @Override
    public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    @Override
    public Object clone();

    @Override
    public int compareTo(
        com.dasannetworks.vn.sb.model.RmaRequestDevice rmaRequestDevice);

    @Override
    public int hashCode();

    @Override
    public CacheModel<com.dasannetworks.vn.sb.model.RmaRequestDevice> toCacheModel();

    @Override
    public com.dasannetworks.vn.sb.model.RmaRequestDevice toEscapedModel();

    @Override
    public com.dasannetworks.vn.sb.model.RmaRequestDevice toUnescapedModel();

    @Override
    public String toString();

    @Override
    public String toXmlString();
}
