package com.dasannetworks.vn.sb.model.impl;

import com.dasannetworks.vn.sb.model.UploadFile;
import com.dasannetworks.vn.sb.model.UploadFileModel;
import com.dasannetworks.vn.sb.model.UploadFileSoap;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;
import com.liferay.portal.util.PortalUtil;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the UploadFile service. Represents a row in the &quot;tms_UploadFile&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.dasannetworks.vn.sb.model.UploadFileModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link UploadFileImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see UploadFileImpl
 * @see com.dasannetworks.vn.sb.model.UploadFile
 * @see com.dasannetworks.vn.sb.model.UploadFileModel
 * @generated
 */
@JSON(strict = true)
public class UploadFileModelImpl extends BaseModelImpl<UploadFile>
    implements UploadFileModel {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a upload file model instance should use the {@link com.dasannetworks.vn.sb.model.UploadFile} interface instead.
     */
    public static final String TABLE_NAME = "tms_UploadFile";
    public static final Object[][] TABLE_COLUMNS = {
            { "uploadFileId", Types.BIGINT },
            { "groupId", Types.BIGINT },
            { "companyId", Types.BIGINT },
            { "userId", Types.BIGINT },
            { "userName", Types.VARCHAR },
            { "createDate", Types.TIMESTAMP },
            { "modifiedDate", Types.TIMESTAMP },
            { "status", Types.VARCHAR },
            { "fileName", Types.VARCHAR }
        };
    public static final String TABLE_SQL_CREATE = "create table tms_UploadFile (uploadFileId LONG not null primary key,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,status VARCHAR(75) null,fileName VARCHAR(75) null)";
    public static final String TABLE_SQL_DROP = "drop table tms_UploadFile";
    public static final String ORDER_BY_JPQL = " ORDER BY uploadFile.uploadFileId ASC";
    public static final String ORDER_BY_SQL = " ORDER BY tms_UploadFile.uploadFileId ASC";
    public static final String DATA_SOURCE = "liferayDataSource";
    public static final String SESSION_FACTORY = "liferaySessionFactory";
    public static final String TX_MANAGER = "liferayTransactionManager";
    public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
                "value.object.entity.cache.enabled.com.dasannetworks.vn.sb.model.UploadFile"),
            true);
    public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
                "value.object.finder.cache.enabled.com.dasannetworks.vn.sb.model.UploadFile"),
            true);
    public static final boolean COLUMN_BITMASK_ENABLED = false;
    public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
                "lock.expiration.time.com.dasannetworks.vn.sb.model.UploadFile"));
    private static ClassLoader _classLoader = UploadFile.class.getClassLoader();
    private static Class<?>[] _escapedModelInterfaces = new Class[] {
            UploadFile.class
        };
    private long _uploadFileId;
    private long _groupId;
    private long _companyId;
    private long _userId;
    private String _userUuid;
    private String _userName;
    private Date _createDate;
    private Date _modifiedDate;
    private String _status;
    private String _fileName;
    private UploadFile _escapedModel;

    public UploadFileModelImpl() {
    }

    /**
     * Converts the soap model instance into a normal model instance.
     *
     * @param soapModel the soap model instance to convert
     * @return the normal model instance
     */
    public static UploadFile toModel(UploadFileSoap soapModel) {
        if (soapModel == null) {
            return null;
        }

        UploadFile model = new UploadFileImpl();

        model.setUploadFileId(soapModel.getUploadFileId());
        model.setGroupId(soapModel.getGroupId());
        model.setCompanyId(soapModel.getCompanyId());
        model.setUserId(soapModel.getUserId());
        model.setUserName(soapModel.getUserName());
        model.setCreateDate(soapModel.getCreateDate());
        model.setModifiedDate(soapModel.getModifiedDate());
        model.setStatus(soapModel.getStatus());
        model.setFileName(soapModel.getFileName());

        return model;
    }

    /**
     * Converts the soap model instances into normal model instances.
     *
     * @param soapModels the soap model instances to convert
     * @return the normal model instances
     */
    public static List<UploadFile> toModels(UploadFileSoap[] soapModels) {
        if (soapModels == null) {
            return null;
        }

        List<UploadFile> models = new ArrayList<UploadFile>(soapModels.length);

        for (UploadFileSoap soapModel : soapModels) {
            models.add(toModel(soapModel));
        }

        return models;
    }

    @Override
    public long getPrimaryKey() {
        return _uploadFileId;
    }

    @Override
    public void setPrimaryKey(long primaryKey) {
        setUploadFileId(primaryKey);
    }

    @Override
    public Serializable getPrimaryKeyObj() {
        return _uploadFileId;
    }

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj) {
        setPrimaryKey(((Long) primaryKeyObj).longValue());
    }

    @Override
    public Class<?> getModelClass() {
        return UploadFile.class;
    }

    @Override
    public String getModelClassName() {
        return UploadFile.class.getName();
    }

    @Override
    public Map<String, Object> getModelAttributes() {
        Map<String, Object> attributes = new HashMap<String, Object>();

        attributes.put("uploadFileId", getUploadFileId());
        attributes.put("groupId", getGroupId());
        attributes.put("companyId", getCompanyId());
        attributes.put("userId", getUserId());
        attributes.put("userName", getUserName());
        attributes.put("createDate", getCreateDate());
        attributes.put("modifiedDate", getModifiedDate());
        attributes.put("status", getStatus());
        attributes.put("fileName", getFileName());

        return attributes;
    }

    @Override
    public void setModelAttributes(Map<String, Object> attributes) {
        Long uploadFileId = (Long) attributes.get("uploadFileId");

        if (uploadFileId != null) {
            setUploadFileId(uploadFileId);
        }

        Long groupId = (Long) attributes.get("groupId");

        if (groupId != null) {
            setGroupId(groupId);
        }

        Long companyId = (Long) attributes.get("companyId");

        if (companyId != null) {
            setCompanyId(companyId);
        }

        Long userId = (Long) attributes.get("userId");

        if (userId != null) {
            setUserId(userId);
        }

        String userName = (String) attributes.get("userName");

        if (userName != null) {
            setUserName(userName);
        }

        Date createDate = (Date) attributes.get("createDate");

        if (createDate != null) {
            setCreateDate(createDate);
        }

        Date modifiedDate = (Date) attributes.get("modifiedDate");

        if (modifiedDate != null) {
            setModifiedDate(modifiedDate);
        }

        String status = (String) attributes.get("status");

        if (status != null) {
            setStatus(status);
        }

        String fileName = (String) attributes.get("fileName");

        if (fileName != null) {
            setFileName(fileName);
        }
    }

    @JSON
    @Override
    public long getUploadFileId() {
        return _uploadFileId;
    }

    @Override
    public void setUploadFileId(long uploadFileId) {
        _uploadFileId = uploadFileId;
    }

    @JSON
    @Override
    public long getGroupId() {
        return _groupId;
    }

    @Override
    public void setGroupId(long groupId) {
        _groupId = groupId;
    }

    @JSON
    @Override
    public long getCompanyId() {
        return _companyId;
    }

    @Override
    public void setCompanyId(long companyId) {
        _companyId = companyId;
    }

    @JSON
    @Override
    public long getUserId() {
        return _userId;
    }

    @Override
    public void setUserId(long userId) {
        _userId = userId;
    }

    @Override
    public String getUserUuid() throws SystemException {
        return PortalUtil.getUserValue(getUserId(), "uuid", _userUuid);
    }

    @Override
    public void setUserUuid(String userUuid) {
        _userUuid = userUuid;
    }

    @JSON
    @Override
    public String getUserName() {
        if (_userName == null) {
            return StringPool.BLANK;
        } else {
            return _userName;
        }
    }

    @Override
    public void setUserName(String userName) {
        _userName = userName;
    }

    @JSON
    @Override
    public Date getCreateDate() {
        return _createDate;
    }

    @Override
    public void setCreateDate(Date createDate) {
        _createDate = createDate;
    }

    @JSON
    @Override
    public Date getModifiedDate() {
        return _modifiedDate;
    }

    @Override
    public void setModifiedDate(Date modifiedDate) {
        _modifiedDate = modifiedDate;
    }

    @JSON
    @Override
    public String getStatus() {
        if (_status == null) {
            return StringPool.BLANK;
        } else {
            return _status;
        }
    }

    @Override
    public void setStatus(String status) {
        _status = status;
    }

    @JSON
    @Override
    public String getFileName() {
        if (_fileName == null) {
            return StringPool.BLANK;
        } else {
            return _fileName;
        }
    }

    @Override
    public void setFileName(String fileName) {
        _fileName = fileName;
    }

    @Override
    public ExpandoBridge getExpandoBridge() {
        return ExpandoBridgeFactoryUtil.getExpandoBridge(getCompanyId(),
            UploadFile.class.getName(), getPrimaryKey());
    }

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
        ExpandoBridge expandoBridge = getExpandoBridge();

        expandoBridge.setAttributes(serviceContext);
    }

    @Override
    public UploadFile toEscapedModel() {
        if (_escapedModel == null) {
            _escapedModel = (UploadFile) ProxyUtil.newProxyInstance(_classLoader,
                    _escapedModelInterfaces, new AutoEscapeBeanHandler(this));
        }

        return _escapedModel;
    }

    @Override
    public Object clone() {
        UploadFileImpl uploadFileImpl = new UploadFileImpl();

        uploadFileImpl.setUploadFileId(getUploadFileId());
        uploadFileImpl.setGroupId(getGroupId());
        uploadFileImpl.setCompanyId(getCompanyId());
        uploadFileImpl.setUserId(getUserId());
        uploadFileImpl.setUserName(getUserName());
        uploadFileImpl.setCreateDate(getCreateDate());
        uploadFileImpl.setModifiedDate(getModifiedDate());
        uploadFileImpl.setStatus(getStatus());
        uploadFileImpl.setFileName(getFileName());

        uploadFileImpl.resetOriginalValues();

        return uploadFileImpl;
    }

    @Override
    public int compareTo(UploadFile uploadFile) {
        long primaryKey = uploadFile.getPrimaryKey();

        if (getPrimaryKey() < primaryKey) {
            return -1;
        } else if (getPrimaryKey() > primaryKey) {
            return 1;
        } else {
            return 0;
        }
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }

        if (!(obj instanceof UploadFile)) {
            return false;
        }

        UploadFile uploadFile = (UploadFile) obj;

        long primaryKey = uploadFile.getPrimaryKey();

        if (getPrimaryKey() == primaryKey) {
            return true;
        } else {
            return false;
        }
    }

    @Override
    public int hashCode() {
        return (int) getPrimaryKey();
    }

    @Override
    public void resetOriginalValues() {
    }

    @Override
    public CacheModel<UploadFile> toCacheModel() {
        UploadFileCacheModel uploadFileCacheModel = new UploadFileCacheModel();

        uploadFileCacheModel.uploadFileId = getUploadFileId();

        uploadFileCacheModel.groupId = getGroupId();

        uploadFileCacheModel.companyId = getCompanyId();

        uploadFileCacheModel.userId = getUserId();

        uploadFileCacheModel.userName = getUserName();

        String userName = uploadFileCacheModel.userName;

        if ((userName != null) && (userName.length() == 0)) {
            uploadFileCacheModel.userName = null;
        }

        Date createDate = getCreateDate();

        if (createDate != null) {
            uploadFileCacheModel.createDate = createDate.getTime();
        } else {
            uploadFileCacheModel.createDate = Long.MIN_VALUE;
        }

        Date modifiedDate = getModifiedDate();

        if (modifiedDate != null) {
            uploadFileCacheModel.modifiedDate = modifiedDate.getTime();
        } else {
            uploadFileCacheModel.modifiedDate = Long.MIN_VALUE;
        }

        uploadFileCacheModel.status = getStatus();

        String status = uploadFileCacheModel.status;

        if ((status != null) && (status.length() == 0)) {
            uploadFileCacheModel.status = null;
        }

        uploadFileCacheModel.fileName = getFileName();

        String fileName = uploadFileCacheModel.fileName;

        if ((fileName != null) && (fileName.length() == 0)) {
            uploadFileCacheModel.fileName = null;
        }

        return uploadFileCacheModel;
    }

    @Override
    public String toString() {
        StringBundler sb = new StringBundler(19);

        sb.append("{uploadFileId=");
        sb.append(getUploadFileId());
        sb.append(", groupId=");
        sb.append(getGroupId());
        sb.append(", companyId=");
        sb.append(getCompanyId());
        sb.append(", userId=");
        sb.append(getUserId());
        sb.append(", userName=");
        sb.append(getUserName());
        sb.append(", createDate=");
        sb.append(getCreateDate());
        sb.append(", modifiedDate=");
        sb.append(getModifiedDate());
        sb.append(", status=");
        sb.append(getStatus());
        sb.append(", fileName=");
        sb.append(getFileName());
        sb.append("}");

        return sb.toString();
    }

    @Override
    public String toXmlString() {
        StringBundler sb = new StringBundler(31);

        sb.append("<model><model-name>");
        sb.append("com.dasannetworks.vn.sb.model.UploadFile");
        sb.append("</model-name>");

        sb.append(
            "<column><column-name>uploadFileId</column-name><column-value><![CDATA[");
        sb.append(getUploadFileId());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>groupId</column-name><column-value><![CDATA[");
        sb.append(getGroupId());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>companyId</column-name><column-value><![CDATA[");
        sb.append(getCompanyId());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>userId</column-name><column-value><![CDATA[");
        sb.append(getUserId());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>userName</column-name><column-value><![CDATA[");
        sb.append(getUserName());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>createDate</column-name><column-value><![CDATA[");
        sb.append(getCreateDate());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>modifiedDate</column-name><column-value><![CDATA[");
        sb.append(getModifiedDate());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>status</column-name><column-value><![CDATA[");
        sb.append(getStatus());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>fileName</column-name><column-value><![CDATA[");
        sb.append(getFileName());
        sb.append("]]></column-value></column>");

        sb.append("</model>");

        return sb.toString();
    }
}
