package com.dasannetworks.vn.sb.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.StagedGroupedModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the HandOverForm service. Represents a row in the &quot;tms_HandOverForm&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.dasannetworks.vn.sb.model.impl.HandOverFormModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.dasannetworks.vn.sb.model.impl.HandOverFormImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see HandOverForm
 * @see com.dasannetworks.vn.sb.model.impl.HandOverFormImpl
 * @see com.dasannetworks.vn.sb.model.impl.HandOverFormModelImpl
 * @generated
 */
public interface HandOverFormModel extends BaseModel<HandOverForm>,
    StagedGroupedModel {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this interface directly. All methods that expect a hand over form model instance should use the {@link HandOverForm} interface instead.
     */

    /**
     * Returns the primary key of this hand over form.
     *
     * @return the primary key of this hand over form
     */
    public long getPrimaryKey();

    /**
     * Sets the primary key of this hand over form.
     *
     * @param primaryKey the primary key of this hand over form
     */
    public void setPrimaryKey(long primaryKey);

    /**
     * Returns the uuid of this hand over form.
     *
     * @return the uuid of this hand over form
     */
    @AutoEscape
    @Override
    public String getUuid();

    /**
     * Sets the uuid of this hand over form.
     *
     * @param uuid the uuid of this hand over form
     */
    @Override
    public void setUuid(String uuid);

    /**
     * Returns the hand over form ID of this hand over form.
     *
     * @return the hand over form ID of this hand over form
     */
    public long getHandOverFormId();

    /**
     * Sets the hand over form ID of this hand over form.
     *
     * @param handOverFormId the hand over form ID of this hand over form
     */
    public void setHandOverFormId(long handOverFormId);

    /**
     * Returns the company ID of this hand over form.
     *
     * @return the company ID of this hand over form
     */
    @Override
    public long getCompanyId();

    /**
     * Sets the company ID of this hand over form.
     *
     * @param companyId the company ID of this hand over form
     */
    @Override
    public void setCompanyId(long companyId);

    /**
     * Returns the user ID of this hand over form.
     *
     * @return the user ID of this hand over form
     */
    @Override
    public long getUserId();

    /**
     * Sets the user ID of this hand over form.
     *
     * @param userId the user ID of this hand over form
     */
    @Override
    public void setUserId(long userId);

    /**
     * Returns the user uuid of this hand over form.
     *
     * @return the user uuid of this hand over form
     * @throws SystemException if a system exception occurred
     */
    @Override
    public String getUserUuid() throws SystemException;

    /**
     * Sets the user uuid of this hand over form.
     *
     * @param userUuid the user uuid of this hand over form
     */
    @Override
    public void setUserUuid(String userUuid);

    /**
     * Returns the user name of this hand over form.
     *
     * @return the user name of this hand over form
     */
    @AutoEscape
    @Override
    public String getUserName();

    /**
     * Sets the user name of this hand over form.
     *
     * @param userName the user name of this hand over form
     */
    @Override
    public void setUserName(String userName);

    /**
     * Returns the create date of this hand over form.
     *
     * @return the create date of this hand over form
     */
    @Override
    public Date getCreateDate();

    /**
     * Sets the create date of this hand over form.
     *
     * @param createDate the create date of this hand over form
     */
    @Override
    public void setCreateDate(Date createDate);

    /**
     * Returns the modified date of this hand over form.
     *
     * @return the modified date of this hand over form
     */
    @Override
    public Date getModifiedDate();

    /**
     * Sets the modified date of this hand over form.
     *
     * @param modifiedDate the modified date of this hand over form
     */
    @Override
    public void setModifiedDate(Date modifiedDate);

    /**
     * Returns the group ID of this hand over form.
     *
     * @return the group ID of this hand over form
     */
    @Override
    public long getGroupId();

    /**
     * Sets the group ID of this hand over form.
     *
     * @param groupId the group ID of this hand over form
     */
    @Override
    public void setGroupId(long groupId);

    /**
     * Returns the customer code of this hand over form.
     *
     * @return the customer code of this hand over form
     */
    @AutoEscape
    public String getCustomerCode();

    /**
     * Sets the customer code of this hand over form.
     *
     * @param customerCode the customer code of this hand over form
     */
    public void setCustomerCode(String customerCode);

    /**
     * Returns the contact point of this hand over form.
     *
     * @return the contact point of this hand over form
     */
    @AutoEscape
    public String getContactPoint();

    /**
     * Sets the contact point of this hand over form.
     *
     * @param contactPoint the contact point of this hand over form
     */
    public void setContactPoint(String contactPoint);

    /**
     * Returns the email of this hand over form.
     *
     * @return the email of this hand over form
     */
    @AutoEscape
    public String getEmail();

    /**
     * Sets the email of this hand over form.
     *
     * @param email the email of this hand over form
     */
    public void setEmail(String email);

    /**
     * Returns the phone of this hand over form.
     *
     * @return the phone of this hand over form
     */
    @AutoEscape
    public String getPhone();

    /**
     * Sets the phone of this hand over form.
     *
     * @param phone the phone of this hand over form
     */
    public void setPhone(String phone);

    /**
     * Returns the location of this hand over form.
     *
     * @return the location of this hand over form
     */
    @AutoEscape
    public String getLocation();

    /**
     * Sets the location of this hand over form.
     *
     * @param location the location of this hand over form
     */
    public void setLocation(String location);

    /**
     * Returns the person in charge of this hand over form.
     *
     * @return the person in charge of this hand over form
     */
    @AutoEscape
    public String getPersonInCharge();

    /**
     * Sets the person in charge of this hand over form.
     *
     * @param personInCharge the person in charge of this hand over form
     */
    public void setPersonInCharge(String personInCharge);

    /**
     * Returns the hand over form number of this hand over form.
     *
     * @return the hand over form number of this hand over form
     */
    @AutoEscape
    public String getHandOverFormNumber();

    /**
     * Sets the hand over form number of this hand over form.
     *
     * @param handOverFormNumber the hand over form number of this hand over form
     */
    public void setHandOverFormNumber(String handOverFormNumber);

    /**
     * Returns the note of this hand over form.
     *
     * @return the note of this hand over form
     */
    @AutoEscape
    public String getNote();

    /**
     * Sets the note of this hand over form.
     *
     * @param note the note of this hand over form
     */
    public void setNote(String note);

    /**
     * Returns the assign date of this hand over form.
     *
     * @return the assign date of this hand over form
     */
    public Date getAssignDate();

    /**
     * Sets the assign date of this hand over form.
     *
     * @param assignDate the assign date of this hand over form
     */
    public void setAssignDate(Date assignDate);

    /**
     * Returns the estimated return date of this hand over form.
     *
     * @return the estimated return date of this hand over form
     */
    public Date getEstimatedReturnDate();

    /**
     * Sets the estimated return date of this hand over form.
     *
     * @param estimatedReturnDate the estimated return date of this hand over form
     */
    public void setEstimatedReturnDate(Date estimatedReturnDate);

    /**
     * Returns the status of this hand over form.
     *
     * @return the status of this hand over form
     */
    public int getStatus();

    /**
     * Sets the status of this hand over form.
     *
     * @param status the status of this hand over form
     */
    public void setStatus(int status);

    /**
     * Returns the status by user ID of this hand over form.
     *
     * @return the status by user ID of this hand over form
     */
    public long getStatusByUserId();

    /**
     * Sets the status by user ID of this hand over form.
     *
     * @param statusByUserId the status by user ID of this hand over form
     */
    public void setStatusByUserId(long statusByUserId);

    /**
     * Returns the status by user uuid of this hand over form.
     *
     * @return the status by user uuid of this hand over form
     * @throws SystemException if a system exception occurred
     */
    public String getStatusByUserUuid() throws SystemException;

    /**
     * Sets the status by user uuid of this hand over form.
     *
     * @param statusByUserUuid the status by user uuid of this hand over form
     */
    public void setStatusByUserUuid(String statusByUserUuid);

    /**
     * Returns the status date of this hand over form.
     *
     * @return the status date of this hand over form
     */
    public Date getStatusDate();

    /**
     * Sets the status date of this hand over form.
     *
     * @param statusDate the status date of this hand over form
     */
    public void setStatusDate(Date statusDate);

    /**
     * Returns the test ID of this hand over form.
     *
     * @return the test ID of this hand over form
     */
    public long getTestId();

    /**
     * Sets the test ID of this hand over form.
     *
     * @param testId the test ID of this hand over form
     */
    public void setTestId(long testId);

    @Override
    public boolean isNew();

    @Override
    public void setNew(boolean n);

    @Override
    public boolean isCachedModel();

    @Override
    public void setCachedModel(boolean cachedModel);

    @Override
    public boolean isEscapedModel();

    @Override
    public Serializable getPrimaryKeyObj();

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj);

    @Override
    public ExpandoBridge getExpandoBridge();

    @Override
    public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

    @Override
    public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    @Override
    public Object clone();

    @Override
    public int compareTo(
        com.dasannetworks.vn.sb.model.HandOverForm handOverForm);

    @Override
    public int hashCode();

    @Override
    public CacheModel<com.dasannetworks.vn.sb.model.HandOverForm> toCacheModel();

    @Override
    public com.dasannetworks.vn.sb.model.HandOverForm toEscapedModel();

    @Override
    public com.dasannetworks.vn.sb.model.HandOverForm toUnescapedModel();

    @Override
    public String toString();

    @Override
    public String toXmlString();
}
