package com.dasannetworks.vn.sb.model;

import com.dasannetworks.vn.sb.service.persistence.RmaRequestDevicePK;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.AuditedModel;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the RmaRequestDevice service. Represents a row in the &quot;tms_RmaRequestDevice&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.dasannetworks.vn.sb.model.impl.RmaRequestDeviceModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.dasannetworks.vn.sb.model.impl.RmaRequestDeviceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see RmaRequestDevice
 * @see com.dasannetworks.vn.sb.model.impl.RmaRequestDeviceImpl
 * @see com.dasannetworks.vn.sb.model.impl.RmaRequestDeviceModelImpl
 * @generated
 */
public interface RmaRequestDeviceModel extends AuditedModel,
    BaseModel<RmaRequestDevice> {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this interface directly. All methods that expect a rma request device model instance should use the {@link RmaRequestDevice} interface instead.
     */

    /**
     * Returns the primary key of this rma request device.
     *
     * @return the primary key of this rma request device
     */
    public RmaRequestDevicePK getPrimaryKey();

    /**
     * Sets the primary key of this rma request device.
     *
     * @param primaryKey the primary key of this rma request device
     */
    public void setPrimaryKey(RmaRequestDevicePK primaryKey);

    /**
     * Returns the rma request ID of this rma request device.
     *
     * @return the rma request ID of this rma request device
     */
    public long getRmaRequestId();

    /**
     * Sets the rma request ID of this rma request device.
     *
     * @param rmaRequestId the rma request ID of this rma request device
     */
    public void setRmaRequestId(long rmaRequestId);

    /**
     * Returns the device ID of this rma request device.
     *
     * @return the device ID of this rma request device
     */
    public long getDeviceId();

    /**
     * Sets the device ID of this rma request device.
     *
     * @param deviceId the device ID of this rma request device
     */
    public void setDeviceId(long deviceId);

    /**
     * Returns the company ID of this rma request device.
     *
     * @return the company ID of this rma request device
     */
    @Override
    public long getCompanyId();

    /**
     * Sets the company ID of this rma request device.
     *
     * @param companyId the company ID of this rma request device
     */
    @Override
    public void setCompanyId(long companyId);

    /**
     * Returns the user ID of this rma request device.
     *
     * @return the user ID of this rma request device
     */
    @Override
    public long getUserId();

    /**
     * Sets the user ID of this rma request device.
     *
     * @param userId the user ID of this rma request device
     */
    @Override
    public void setUserId(long userId);

    /**
     * Returns the user uuid of this rma request device.
     *
     * @return the user uuid of this rma request device
     * @throws SystemException if a system exception occurred
     */
    @Override
    public String getUserUuid() throws SystemException;

    /**
     * Sets the user uuid of this rma request device.
     *
     * @param userUuid the user uuid of this rma request device
     */
    @Override
    public void setUserUuid(String userUuid);

    /**
     * Returns the user name of this rma request device.
     *
     * @return the user name of this rma request device
     */
    @AutoEscape
    @Override
    public String getUserName();

    /**
     * Sets the user name of this rma request device.
     *
     * @param userName the user name of this rma request device
     */
    @Override
    public void setUserName(String userName);

    /**
     * Returns the create date of this rma request device.
     *
     * @return the create date of this rma request device
     */
    @Override
    public Date getCreateDate();

    /**
     * Sets the create date of this rma request device.
     *
     * @param createDate the create date of this rma request device
     */
    @Override
    public void setCreateDate(Date createDate);

    /**
     * Returns the modified date of this rma request device.
     *
     * @return the modified date of this rma request device
     */
    @Override
    public Date getModifiedDate();

    /**
     * Sets the modified date of this rma request device.
     *
     * @param modifiedDate the modified date of this rma request device
     */
    @Override
    public void setModifiedDate(Date modifiedDate);

    /**
     * Returns the fault note of this rma request device.
     *
     * @return the fault note of this rma request device
     */
    @AutoEscape
    public String getFaultNote();

    /**
     * Sets the fault note of this rma request device.
     *
     * @param faultNote the fault note of this rma request device
     */
    public void setFaultNote(String faultNote);

    /**
     * Returns the status of this rma request device.
     *
     * @return the status of this rma request device
     */
    @AutoEscape
    public String getStatus();

    /**
     * Sets the status of this rma request device.
     *
     * @param status the status of this rma request device
     */
    public void setStatus(String status);

    @Override
    public boolean isNew();

    @Override
    public void setNew(boolean n);

    @Override
    public boolean isCachedModel();

    @Override
    public void setCachedModel(boolean cachedModel);

    @Override
    public boolean isEscapedModel();

    @Override
    public Serializable getPrimaryKeyObj();

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj);

    @Override
    public ExpandoBridge getExpandoBridge();

    @Override
    public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

    @Override
    public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    @Override
    public Object clone();

    @Override
    public int compareTo(
        com.dasannetworks.vn.sb.model.RmaRequestDevice rmaRequestDevice);

    @Override
    public int hashCode();

    @Override
    public CacheModel<com.dasannetworks.vn.sb.model.RmaRequestDevice> toCacheModel();

    @Override
    public com.dasannetworks.vn.sb.model.RmaRequestDevice toEscapedModel();

    @Override
    public com.dasannetworks.vn.sb.model.RmaRequestDevice toUnescapedModel();

    @Override
    public String toString();

    @Override
    public String toXmlString();
}
