package com.dasannetworks.vn.sb.model.impl;

import com.dasannetworks.vn.sb.model.RmaRequest;
import com.dasannetworks.vn.sb.service.RmaRequestLocalServiceUtil;

import com.liferay.portal.kernel.exception.SystemException;

/**
 * The extended model base implementation for the RmaRequest service. Represents a row in the &quot;tms_RmaRequest&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link RmaRequestImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see RmaRequestImpl
 * @see com.dasannetworks.vn.sb.model.RmaRequest
 * @generated
 */
public abstract class RmaRequestBaseImpl extends RmaRequestModelImpl
    implements RmaRequest {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a rma request model instance should use the {@link RmaRequest} interface instead.
     */
    @Override
    public void persist() throws SystemException {
        if (this.isNew()) {
            RmaRequestLocalServiceUtil.addRmaRequest(this);
        } else {
            RmaRequestLocalServiceUtil.updateRmaRequest(this);
        }
    }
}
