package com.dasannetworks.vn.sb.model.impl;

import com.dasannetworks.vn.sb.model.RmaRequestDevice;
import com.dasannetworks.vn.sb.model.RmaRequestDeviceModel;
import com.dasannetworks.vn.sb.service.persistence.RmaRequestDevicePK;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.util.PortalUtil;

import java.io.Serializable;

import java.sql.Types;

import java.util.Date;
import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the RmaRequestDevice service. Represents a row in the &quot;tms_RmaRequestDevice&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.dasannetworks.vn.sb.model.RmaRequestDeviceModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link RmaRequestDeviceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see RmaRequestDeviceImpl
 * @see com.dasannetworks.vn.sb.model.RmaRequestDevice
 * @see com.dasannetworks.vn.sb.model.RmaRequestDeviceModel
 * @generated
 */
public class RmaRequestDeviceModelImpl extends BaseModelImpl<RmaRequestDevice>
    implements RmaRequestDeviceModel {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a rma request device model instance should use the {@link com.dasannetworks.vn.sb.model.RmaRequestDevice} interface instead.
     */
    public static final String TABLE_NAME = "tms_RmaRequestDevice";
    public static final Object[][] TABLE_COLUMNS = {
            { "rmaRequestId", Types.BIGINT },
            { "deviceId", Types.BIGINT },
            { "companyId", Types.BIGINT },
            { "userId", Types.BIGINT },
            { "userName", Types.VARCHAR },
            { "createDate", Types.TIMESTAMP },
            { "modifiedDate", Types.TIMESTAMP },
            { "faultNote", Types.VARCHAR },
            { "status", Types.VARCHAR }
        };
    public static final String TABLE_SQL_CREATE = "create table tms_RmaRequestDevice (rmaRequestId LONG not null,deviceId LONG not null,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,faultNote VARCHAR(75) null,status VARCHAR(75) null,primary key (rmaRequestId, deviceId))";
    public static final String TABLE_SQL_DROP = "drop table tms_RmaRequestDevice";
    public static final String ORDER_BY_JPQL = " ORDER BY rmaRequestDevice.id.rmaRequestId ASC, rmaRequestDevice.id.deviceId ASC";
    public static final String ORDER_BY_SQL = " ORDER BY tms_RmaRequestDevice.rmaRequestId ASC, tms_RmaRequestDevice.deviceId ASC";
    public static final String DATA_SOURCE = "liferayDataSource";
    public static final String SESSION_FACTORY = "liferaySessionFactory";
    public static final String TX_MANAGER = "liferayTransactionManager";
    public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
                "value.object.entity.cache.enabled.com.dasannetworks.vn.sb.model.RmaRequestDevice"),
            false);
    public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
                "value.object.finder.cache.enabled.com.dasannetworks.vn.sb.model.RmaRequestDevice"),
            false);
    public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
                "value.object.column.bitmask.enabled.com.dasannetworks.vn.sb.model.RmaRequestDevice"),
            true);
    public static long DEVICEID_COLUMN_BITMASK = 1L;
    public static long RMAREQUESTID_COLUMN_BITMASK = 2L;
    public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
                "lock.expiration.time.com.dasannetworks.vn.sb.model.RmaRequestDevice"));
    private static ClassLoader _classLoader = RmaRequestDevice.class.getClassLoader();
    private static Class<?>[] _escapedModelInterfaces = new Class[] {
            RmaRequestDevice.class
        };
    private long _rmaRequestId;
    private long _originalRmaRequestId;
    private boolean _setOriginalRmaRequestId;
    private long _deviceId;
    private long _originalDeviceId;
    private boolean _setOriginalDeviceId;
    private long _companyId;
    private long _userId;
    private String _userUuid;
    private String _userName;
    private Date _createDate;
    private Date _modifiedDate;
    private String _faultNote;
    private String _status;
    private long _columnBitmask;
    private RmaRequestDevice _escapedModel;

    public RmaRequestDeviceModelImpl() {
    }

    @Override
    public RmaRequestDevicePK getPrimaryKey() {
        return new RmaRequestDevicePK(_rmaRequestId, _deviceId);
    }

    @Override
    public void setPrimaryKey(RmaRequestDevicePK primaryKey) {
        setRmaRequestId(primaryKey.rmaRequestId);
        setDeviceId(primaryKey.deviceId);
    }

    @Override
    public Serializable getPrimaryKeyObj() {
        return new RmaRequestDevicePK(_rmaRequestId, _deviceId);
    }

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj) {
        setPrimaryKey((RmaRequestDevicePK) primaryKeyObj);
    }

    @Override
    public Class<?> getModelClass() {
        return RmaRequestDevice.class;
    }

    @Override
    public String getModelClassName() {
        return RmaRequestDevice.class.getName();
    }

    @Override
    public Map<String, Object> getModelAttributes() {
        Map<String, Object> attributes = new HashMap<String, Object>();

        attributes.put("rmaRequestId", getRmaRequestId());
        attributes.put("deviceId", getDeviceId());
        attributes.put("companyId", getCompanyId());
        attributes.put("userId", getUserId());
        attributes.put("userName", getUserName());
        attributes.put("createDate", getCreateDate());
        attributes.put("modifiedDate", getModifiedDate());
        attributes.put("faultNote", getFaultNote());
        attributes.put("status", getStatus());

        return attributes;
    }

    @Override
    public void setModelAttributes(Map<String, Object> attributes) {
        Long rmaRequestId = (Long) attributes.get("rmaRequestId");

        if (rmaRequestId != null) {
            setRmaRequestId(rmaRequestId);
        }

        Long deviceId = (Long) attributes.get("deviceId");

        if (deviceId != null) {
            setDeviceId(deviceId);
        }

        Long companyId = (Long) attributes.get("companyId");

        if (companyId != null) {
            setCompanyId(companyId);
        }

        Long userId = (Long) attributes.get("userId");

        if (userId != null) {
            setUserId(userId);
        }

        String userName = (String) attributes.get("userName");

        if (userName != null) {
            setUserName(userName);
        }

        Date createDate = (Date) attributes.get("createDate");

        if (createDate != null) {
            setCreateDate(createDate);
        }

        Date modifiedDate = (Date) attributes.get("modifiedDate");

        if (modifiedDate != null) {
            setModifiedDate(modifiedDate);
        }

        String faultNote = (String) attributes.get("faultNote");

        if (faultNote != null) {
            setFaultNote(faultNote);
        }

        String status = (String) attributes.get("status");

        if (status != null) {
            setStatus(status);
        }
    }

    @Override
    public long getRmaRequestId() {
        return _rmaRequestId;
    }

    @Override
    public void setRmaRequestId(long rmaRequestId) {
        _columnBitmask |= RMAREQUESTID_COLUMN_BITMASK;

        if (!_setOriginalRmaRequestId) {
            _setOriginalRmaRequestId = true;

            _originalRmaRequestId = _rmaRequestId;
        }

        _rmaRequestId = rmaRequestId;
    }

    public long getOriginalRmaRequestId() {
        return _originalRmaRequestId;
    }

    @Override
    public long getDeviceId() {
        return _deviceId;
    }

    @Override
    public void setDeviceId(long deviceId) {
        _columnBitmask |= DEVICEID_COLUMN_BITMASK;

        if (!_setOriginalDeviceId) {
            _setOriginalDeviceId = true;

            _originalDeviceId = _deviceId;
        }

        _deviceId = deviceId;
    }

    public long getOriginalDeviceId() {
        return _originalDeviceId;
    }

    @Override
    public long getCompanyId() {
        return _companyId;
    }

    @Override
    public void setCompanyId(long companyId) {
        _companyId = companyId;
    }

    @Override
    public long getUserId() {
        return _userId;
    }

    @Override
    public void setUserId(long userId) {
        _userId = userId;
    }

    @Override
    public String getUserUuid() throws SystemException {
        return PortalUtil.getUserValue(getUserId(), "uuid", _userUuid);
    }

    @Override
    public void setUserUuid(String userUuid) {
        _userUuid = userUuid;
    }

    @Override
    public String getUserName() {
        if (_userName == null) {
            return StringPool.BLANK;
        } else {
            return _userName;
        }
    }

    @Override
    public void setUserName(String userName) {
        _userName = userName;
    }

    @Override
    public Date getCreateDate() {
        return _createDate;
    }

    @Override
    public void setCreateDate(Date createDate) {
        _createDate = createDate;
    }

    @Override
    public Date getModifiedDate() {
        return _modifiedDate;
    }

    @Override
    public void setModifiedDate(Date modifiedDate) {
        _modifiedDate = modifiedDate;
    }

    @Override
    public String getFaultNote() {
        if (_faultNote == null) {
            return StringPool.BLANK;
        } else {
            return _faultNote;
        }
    }

    @Override
    public void setFaultNote(String faultNote) {
        _faultNote = faultNote;
    }

    @Override
    public String getStatus() {
        if (_status == null) {
            return StringPool.BLANK;
        } else {
            return _status;
        }
    }

    @Override
    public void setStatus(String status) {
        _status = status;
    }

    public long getColumnBitmask() {
        return _columnBitmask;
    }

    @Override
    public RmaRequestDevice toEscapedModel() {
        if (_escapedModel == null) {
            _escapedModel = (RmaRequestDevice) ProxyUtil.newProxyInstance(_classLoader,
                    _escapedModelInterfaces, new AutoEscapeBeanHandler(this));
        }

        return _escapedModel;
    }

    @Override
    public Object clone() {
        RmaRequestDeviceImpl rmaRequestDeviceImpl = new RmaRequestDeviceImpl();

        rmaRequestDeviceImpl.setRmaRequestId(getRmaRequestId());
        rmaRequestDeviceImpl.setDeviceId(getDeviceId());
        rmaRequestDeviceImpl.setCompanyId(getCompanyId());
        rmaRequestDeviceImpl.setUserId(getUserId());
        rmaRequestDeviceImpl.setUserName(getUserName());
        rmaRequestDeviceImpl.setCreateDate(getCreateDate());
        rmaRequestDeviceImpl.setModifiedDate(getModifiedDate());
        rmaRequestDeviceImpl.setFaultNote(getFaultNote());
        rmaRequestDeviceImpl.setStatus(getStatus());

        rmaRequestDeviceImpl.resetOriginalValues();

        return rmaRequestDeviceImpl;
    }

    @Override
    public int compareTo(RmaRequestDevice rmaRequestDevice) {
        RmaRequestDevicePK primaryKey = rmaRequestDevice.getPrimaryKey();

        return getPrimaryKey().compareTo(primaryKey);
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }

        if (!(obj instanceof RmaRequestDevice)) {
            return false;
        }

        RmaRequestDevice rmaRequestDevice = (RmaRequestDevice) obj;

        RmaRequestDevicePK primaryKey = rmaRequestDevice.getPrimaryKey();

        if (getPrimaryKey().equals(primaryKey)) {
            return true;
        } else {
            return false;
        }
    }

    @Override
    public int hashCode() {
        return getPrimaryKey().hashCode();
    }

    @Override
    public void resetOriginalValues() {
        RmaRequestDeviceModelImpl rmaRequestDeviceModelImpl = this;

        rmaRequestDeviceModelImpl._originalRmaRequestId = rmaRequestDeviceModelImpl._rmaRequestId;

        rmaRequestDeviceModelImpl._setOriginalRmaRequestId = false;

        rmaRequestDeviceModelImpl._originalDeviceId = rmaRequestDeviceModelImpl._deviceId;

        rmaRequestDeviceModelImpl._setOriginalDeviceId = false;

        rmaRequestDeviceModelImpl._columnBitmask = 0;
    }

    @Override
    public CacheModel<RmaRequestDevice> toCacheModel() {
        RmaRequestDeviceCacheModel rmaRequestDeviceCacheModel = new RmaRequestDeviceCacheModel();

        rmaRequestDeviceCacheModel.rmaRequestId = getRmaRequestId();

        rmaRequestDeviceCacheModel.deviceId = getDeviceId();

        rmaRequestDeviceCacheModel.companyId = getCompanyId();

        rmaRequestDeviceCacheModel.userId = getUserId();

        rmaRequestDeviceCacheModel.userName = getUserName();

        String userName = rmaRequestDeviceCacheModel.userName;

        if ((userName != null) && (userName.length() == 0)) {
            rmaRequestDeviceCacheModel.userName = null;
        }

        Date createDate = getCreateDate();

        if (createDate != null) {
            rmaRequestDeviceCacheModel.createDate = createDate.getTime();
        } else {
            rmaRequestDeviceCacheModel.createDate = Long.MIN_VALUE;
        }

        Date modifiedDate = getModifiedDate();

        if (modifiedDate != null) {
            rmaRequestDeviceCacheModel.modifiedDate = modifiedDate.getTime();
        } else {
            rmaRequestDeviceCacheModel.modifiedDate = Long.MIN_VALUE;
        }

        rmaRequestDeviceCacheModel.faultNote = getFaultNote();

        String faultNote = rmaRequestDeviceCacheModel.faultNote;

        if ((faultNote != null) && (faultNote.length() == 0)) {
            rmaRequestDeviceCacheModel.faultNote = null;
        }

        rmaRequestDeviceCacheModel.status = getStatus();

        String status = rmaRequestDeviceCacheModel.status;

        if ((status != null) && (status.length() == 0)) {
            rmaRequestDeviceCacheModel.status = null;
        }

        return rmaRequestDeviceCacheModel;
    }

    @Override
    public String toString() {
        StringBundler sb = new StringBundler(19);

        sb.append("{rmaRequestId=");
        sb.append(getRmaRequestId());
        sb.append(", deviceId=");
        sb.append(getDeviceId());
        sb.append(", companyId=");
        sb.append(getCompanyId());
        sb.append(", userId=");
        sb.append(getUserId());
        sb.append(", userName=");
        sb.append(getUserName());
        sb.append(", createDate=");
        sb.append(getCreateDate());
        sb.append(", modifiedDate=");
        sb.append(getModifiedDate());
        sb.append(", faultNote=");
        sb.append(getFaultNote());
        sb.append(", status=");
        sb.append(getStatus());
        sb.append("}");

        return sb.toString();
    }

    @Override
    public String toXmlString() {
        StringBundler sb = new StringBundler(31);

        sb.append("<model><model-name>");
        sb.append("com.dasannetworks.vn.sb.model.RmaRequestDevice");
        sb.append("</model-name>");

        sb.append(
            "<column><column-name>rmaRequestId</column-name><column-value><![CDATA[");
        sb.append(getRmaRequestId());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>deviceId</column-name><column-value><![CDATA[");
        sb.append(getDeviceId());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>companyId</column-name><column-value><![CDATA[");
        sb.append(getCompanyId());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>userId</column-name><column-value><![CDATA[");
        sb.append(getUserId());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>userName</column-name><column-value><![CDATA[");
        sb.append(getUserName());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>createDate</column-name><column-value><![CDATA[");
        sb.append(getCreateDate());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>modifiedDate</column-name><column-value><![CDATA[");
        sb.append(getModifiedDate());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>faultNote</column-name><column-value><![CDATA[");
        sb.append(getFaultNote());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>status</column-name><column-value><![CDATA[");
        sb.append(getStatus());
        sb.append("]]></column-value></column>");

        sb.append("</model>");

        return sb.toString();
    }
}
