package com.dasannetworks.tms.sb.service.base;

import com.dasannetworks.tms.sb.model.Book;
import com.dasannetworks.tms.sb.service.BookService;
import com.dasannetworks.tms.sb.service.persistence.BookPersistence;
import com.dasannetworks.tms.sb.service.persistence.ContactPersistence;
import com.dasannetworks.tms.sb.service.persistence.DevicePersistence;
import com.dasannetworks.tms.sb.service.persistence.FeedbackPersistence;
import com.dasannetworks.tms.sb.service.persistence.FooPersistence;
import com.dasannetworks.tms.sb.service.persistence.StudentPersistence;

import com.liferay.portal.kernel.bean.BeanReference;
import com.liferay.portal.kernel.bean.IdentifiableBean;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.service.BaseServiceImpl;
import com.liferay.portal.service.persistence.ClassNamePersistence;
import com.liferay.portal.service.persistence.UserPersistence;

import com.liferay.portlet.expando.service.persistence.ExpandoRowPersistence;
import com.liferay.portlet.expando.service.persistence.ExpandoTablePersistence;
import com.liferay.portlet.expando.service.persistence.ExpandoValuePersistence;

import javax.sql.DataSource;

/**
 * Provides the base implementation for the book remote service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.dasannetworks.tms.sb.service.impl.BookServiceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see com.dasannetworks.tms.sb.service.impl.BookServiceImpl
 * @see com.dasannetworks.tms.sb.service.BookServiceUtil
 * @generated
 */
public abstract class BookServiceBaseImpl extends BaseServiceImpl
    implements BookService, IdentifiableBean {
    @BeanReference(type = com.dasannetworks.tms.sb.service.BookLocalService.class)
    protected com.dasannetworks.tms.sb.service.BookLocalService bookLocalService;
    @BeanReference(type = com.dasannetworks.tms.sb.service.BookService.class)
    protected com.dasannetworks.tms.sb.service.BookService bookService;
    @BeanReference(type = BookPersistence.class)
    protected BookPersistence bookPersistence;
    @BeanReference(type = com.dasannetworks.tms.sb.service.ContactLocalService.class)
    protected com.dasannetworks.tms.sb.service.ContactLocalService contactLocalService;
    @BeanReference(type = com.dasannetworks.tms.sb.service.ContactService.class)
    protected com.dasannetworks.tms.sb.service.ContactService contactService;
    @BeanReference(type = ContactPersistence.class)
    protected ContactPersistence contactPersistence;
    @BeanReference(type = com.dasannetworks.tms.sb.service.DeviceLocalService.class)
    protected com.dasannetworks.tms.sb.service.DeviceLocalService deviceLocalService;
    @BeanReference(type = com.dasannetworks.tms.sb.service.DeviceService.class)
    protected com.dasannetworks.tms.sb.service.DeviceService deviceService;
    @BeanReference(type = DevicePersistence.class)
    protected DevicePersistence devicePersistence;
    @BeanReference(type = com.dasannetworks.tms.sb.service.FeedbackLocalService.class)
    protected com.dasannetworks.tms.sb.service.FeedbackLocalService feedbackLocalService;
    @BeanReference(type = com.dasannetworks.tms.sb.service.FeedbackService.class)
    protected com.dasannetworks.tms.sb.service.FeedbackService feedbackService;
    @BeanReference(type = FeedbackPersistence.class)
    protected FeedbackPersistence feedbackPersistence;
    @BeanReference(type = com.dasannetworks.tms.sb.service.FooLocalService.class)
    protected com.dasannetworks.tms.sb.service.FooLocalService fooLocalService;
    @BeanReference(type = com.dasannetworks.tms.sb.service.FooService.class)
    protected com.dasannetworks.tms.sb.service.FooService fooService;
    @BeanReference(type = FooPersistence.class)
    protected FooPersistence fooPersistence;
    @BeanReference(type = com.dasannetworks.tms.sb.service.StudentLocalService.class)
    protected com.dasannetworks.tms.sb.service.StudentLocalService studentLocalService;
    @BeanReference(type = com.dasannetworks.tms.sb.service.StudentService.class)
    protected com.dasannetworks.tms.sb.service.StudentService studentService;
    @BeanReference(type = StudentPersistence.class)
    protected StudentPersistence studentPersistence;
    @BeanReference(type = com.liferay.counter.service.CounterLocalService.class)
    protected com.liferay.counter.service.CounterLocalService counterLocalService;
    @BeanReference(type = com.liferay.portal.service.ClassNameLocalService.class)
    protected com.liferay.portal.service.ClassNameLocalService classNameLocalService;
    @BeanReference(type = com.liferay.portal.service.ClassNameService.class)
    protected com.liferay.portal.service.ClassNameService classNameService;
    @BeanReference(type = ClassNamePersistence.class)
    protected ClassNamePersistence classNamePersistence;
    @BeanReference(type = com.liferay.portal.service.ResourceLocalService.class)
    protected com.liferay.portal.service.ResourceLocalService resourceLocalService;
    @BeanReference(type = com.liferay.portal.service.UserLocalService.class)
    protected com.liferay.portal.service.UserLocalService userLocalService;
    @BeanReference(type = com.liferay.portal.service.UserService.class)
    protected com.liferay.portal.service.UserService userService;
    @BeanReference(type = UserPersistence.class)
    protected UserPersistence userPersistence;
    @BeanReference(type = com.liferay.portlet.expando.service.ExpandoRowLocalService.class)
    protected com.liferay.portlet.expando.service.ExpandoRowLocalService expandoRowLocalService;
    @BeanReference(type = ExpandoRowPersistence.class)
    protected ExpandoRowPersistence expandoRowPersistence;
    @BeanReference(type = com.liferay.portlet.expando.service.ExpandoTableLocalService.class)
    protected com.liferay.portlet.expando.service.ExpandoTableLocalService expandoTableLocalService;
    @BeanReference(type = ExpandoTablePersistence.class)
    protected ExpandoTablePersistence expandoTablePersistence;
    @BeanReference(type = com.liferay.portlet.expando.service.ExpandoValueLocalService.class)
    protected com.liferay.portlet.expando.service.ExpandoValueLocalService expandoValueLocalService;
    @BeanReference(type = com.liferay.portlet.expando.service.ExpandoValueService.class)
    protected com.liferay.portlet.expando.service.ExpandoValueService expandoValueService;
    @BeanReference(type = ExpandoValuePersistence.class)
    protected ExpandoValuePersistence expandoValuePersistence;
    private String _beanIdentifier;
    private ClassLoader _classLoader;
    private BookServiceClpInvoker _clpInvoker = new BookServiceClpInvoker();

    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. Always use {@link com.dasannetworks.tms.sb.service.BookServiceUtil} to access the book remote service.
     */

    /**
     * Returns the book local service.
     *
     * @return the book local service
     */
    public com.dasannetworks.tms.sb.service.BookLocalService getBookLocalService() {
        return bookLocalService;
    }

    /**
     * Sets the book local service.
     *
     * @param bookLocalService the book local service
     */
    public void setBookLocalService(
        com.dasannetworks.tms.sb.service.BookLocalService bookLocalService) {
        this.bookLocalService = bookLocalService;
    }

    /**
     * Returns the book remote service.
     *
     * @return the book remote service
     */
    public com.dasannetworks.tms.sb.service.BookService getBookService() {
        return bookService;
    }

    /**
     * Sets the book remote service.
     *
     * @param bookService the book remote service
     */
    public void setBookService(
        com.dasannetworks.tms.sb.service.BookService bookService) {
        this.bookService = bookService;
    }

    /**
     * Returns the book persistence.
     *
     * @return the book persistence
     */
    public BookPersistence getBookPersistence() {
        return bookPersistence;
    }

    /**
     * Sets the book persistence.
     *
     * @param bookPersistence the book persistence
     */
    public void setBookPersistence(BookPersistence bookPersistence) {
        this.bookPersistence = bookPersistence;
    }

    /**
     * Returns the contact local service.
     *
     * @return the contact local service
     */
    public com.dasannetworks.tms.sb.service.ContactLocalService getContactLocalService() {
        return contactLocalService;
    }

    /**
     * Sets the contact local service.
     *
     * @param contactLocalService the contact local service
     */
    public void setContactLocalService(
        com.dasannetworks.tms.sb.service.ContactLocalService contactLocalService) {
        this.contactLocalService = contactLocalService;
    }

    /**
     * Returns the contact remote service.
     *
     * @return the contact remote service
     */
    public com.dasannetworks.tms.sb.service.ContactService getContactService() {
        return contactService;
    }

    /**
     * Sets the contact remote service.
     *
     * @param contactService the contact remote service
     */
    public void setContactService(
        com.dasannetworks.tms.sb.service.ContactService contactService) {
        this.contactService = contactService;
    }

    /**
     * Returns the contact persistence.
     *
     * @return the contact persistence
     */
    public ContactPersistence getContactPersistence() {
        return contactPersistence;
    }

    /**
     * Sets the contact persistence.
     *
     * @param contactPersistence the contact persistence
     */
    public void setContactPersistence(ContactPersistence contactPersistence) {
        this.contactPersistence = contactPersistence;
    }

    /**
     * Returns the device local service.
     *
     * @return the device local service
     */
    public com.dasannetworks.tms.sb.service.DeviceLocalService getDeviceLocalService() {
        return deviceLocalService;
    }

    /**
     * Sets the device local service.
     *
     * @param deviceLocalService the device local service
     */
    public void setDeviceLocalService(
        com.dasannetworks.tms.sb.service.DeviceLocalService deviceLocalService) {
        this.deviceLocalService = deviceLocalService;
    }

    /**
     * Returns the device remote service.
     *
     * @return the device remote service
     */
    public com.dasannetworks.tms.sb.service.DeviceService getDeviceService() {
        return deviceService;
    }

    /**
     * Sets the device remote service.
     *
     * @param deviceService the device remote service
     */
    public void setDeviceService(
        com.dasannetworks.tms.sb.service.DeviceService deviceService) {
        this.deviceService = deviceService;
    }

    /**
     * Returns the device persistence.
     *
     * @return the device persistence
     */
    public DevicePersistence getDevicePersistence() {
        return devicePersistence;
    }

    /**
     * Sets the device persistence.
     *
     * @param devicePersistence the device persistence
     */
    public void setDevicePersistence(DevicePersistence devicePersistence) {
        this.devicePersistence = devicePersistence;
    }

    /**
     * Returns the feedback local service.
     *
     * @return the feedback local service
     */
    public com.dasannetworks.tms.sb.service.FeedbackLocalService getFeedbackLocalService() {
        return feedbackLocalService;
    }

    /**
     * Sets the feedback local service.
     *
     * @param feedbackLocalService the feedback local service
     */
    public void setFeedbackLocalService(
        com.dasannetworks.tms.sb.service.FeedbackLocalService feedbackLocalService) {
        this.feedbackLocalService = feedbackLocalService;
    }

    /**
     * Returns the feedback remote service.
     *
     * @return the feedback remote service
     */
    public com.dasannetworks.tms.sb.service.FeedbackService getFeedbackService() {
        return feedbackService;
    }

    /**
     * Sets the feedback remote service.
     *
     * @param feedbackService the feedback remote service
     */
    public void setFeedbackService(
        com.dasannetworks.tms.sb.service.FeedbackService feedbackService) {
        this.feedbackService = feedbackService;
    }

    /**
     * Returns the feedback persistence.
     *
     * @return the feedback persistence
     */
    public FeedbackPersistence getFeedbackPersistence() {
        return feedbackPersistence;
    }

    /**
     * Sets the feedback persistence.
     *
     * @param feedbackPersistence the feedback persistence
     */
    public void setFeedbackPersistence(FeedbackPersistence feedbackPersistence) {
        this.feedbackPersistence = feedbackPersistence;
    }

    /**
     * Returns the foo local service.
     *
     * @return the foo local service
     */
    public com.dasannetworks.tms.sb.service.FooLocalService getFooLocalService() {
        return fooLocalService;
    }

    /**
     * Sets the foo local service.
     *
     * @param fooLocalService the foo local service
     */
    public void setFooLocalService(
        com.dasannetworks.tms.sb.service.FooLocalService fooLocalService) {
        this.fooLocalService = fooLocalService;
    }

    /**
     * Returns the foo remote service.
     *
     * @return the foo remote service
     */
    public com.dasannetworks.tms.sb.service.FooService getFooService() {
        return fooService;
    }

    /**
     * Sets the foo remote service.
     *
     * @param fooService the foo remote service
     */
    public void setFooService(
        com.dasannetworks.tms.sb.service.FooService fooService) {
        this.fooService = fooService;
    }

    /**
     * Returns the foo persistence.
     *
     * @return the foo persistence
     */
    public FooPersistence getFooPersistence() {
        return fooPersistence;
    }

    /**
     * Sets the foo persistence.
     *
     * @param fooPersistence the foo persistence
     */
    public void setFooPersistence(FooPersistence fooPersistence) {
        this.fooPersistence = fooPersistence;
    }

    /**
     * Returns the student local service.
     *
     * @return the student local service
     */
    public com.dasannetworks.tms.sb.service.StudentLocalService getStudentLocalService() {
        return studentLocalService;
    }

    /**
     * Sets the student local service.
     *
     * @param studentLocalService the student local service
     */
    public void setStudentLocalService(
        com.dasannetworks.tms.sb.service.StudentLocalService studentLocalService) {
        this.studentLocalService = studentLocalService;
    }

    /**
     * Returns the student remote service.
     *
     * @return the student remote service
     */
    public com.dasannetworks.tms.sb.service.StudentService getStudentService() {
        return studentService;
    }

    /**
     * Sets the student remote service.
     *
     * @param studentService the student remote service
     */
    public void setStudentService(
        com.dasannetworks.tms.sb.service.StudentService studentService) {
        this.studentService = studentService;
    }

    /**
     * Returns the student persistence.
     *
     * @return the student persistence
     */
    public StudentPersistence getStudentPersistence() {
        return studentPersistence;
    }

    /**
     * Sets the student persistence.
     *
     * @param studentPersistence the student persistence
     */
    public void setStudentPersistence(StudentPersistence studentPersistence) {
        this.studentPersistence = studentPersistence;
    }

    /**
     * Returns the counter local service.
     *
     * @return the counter local service
     */
    public com.liferay.counter.service.CounterLocalService getCounterLocalService() {
        return counterLocalService;
    }

    /**
     * Sets the counter local service.
     *
     * @param counterLocalService the counter local service
     */
    public void setCounterLocalService(
        com.liferay.counter.service.CounterLocalService counterLocalService) {
        this.counterLocalService = counterLocalService;
    }

    /**
     * Returns the class name local service.
     *
     * @return the class name local service
     */
    public com.liferay.portal.service.ClassNameLocalService getClassNameLocalService() {
        return classNameLocalService;
    }

    /**
     * Sets the class name local service.
     *
     * @param classNameLocalService the class name local service
     */
    public void setClassNameLocalService(
        com.liferay.portal.service.ClassNameLocalService classNameLocalService) {
        this.classNameLocalService = classNameLocalService;
    }

    /**
     * Returns the class name remote service.
     *
     * @return the class name remote service
     */
    public com.liferay.portal.service.ClassNameService getClassNameService() {
        return classNameService;
    }

    /**
     * Sets the class name remote service.
     *
     * @param classNameService the class name remote service
     */
    public void setClassNameService(
        com.liferay.portal.service.ClassNameService classNameService) {
        this.classNameService = classNameService;
    }

    /**
     * Returns the class name persistence.
     *
     * @return the class name persistence
     */
    public ClassNamePersistence getClassNamePersistence() {
        return classNamePersistence;
    }

    /**
     * Sets the class name persistence.
     *
     * @param classNamePersistence the class name persistence
     */
    public void setClassNamePersistence(
        ClassNamePersistence classNamePersistence) {
        this.classNamePersistence = classNamePersistence;
    }

    /**
     * Returns the resource local service.
     *
     * @return the resource local service
     */
    public com.liferay.portal.service.ResourceLocalService getResourceLocalService() {
        return resourceLocalService;
    }

    /**
     * Sets the resource local service.
     *
     * @param resourceLocalService the resource local service
     */
    public void setResourceLocalService(
        com.liferay.portal.service.ResourceLocalService resourceLocalService) {
        this.resourceLocalService = resourceLocalService;
    }

    /**
     * Returns the user local service.
     *
     * @return the user local service
     */
    public com.liferay.portal.service.UserLocalService getUserLocalService() {
        return userLocalService;
    }

    /**
     * Sets the user local service.
     *
     * @param userLocalService the user local service
     */
    public void setUserLocalService(
        com.liferay.portal.service.UserLocalService userLocalService) {
        this.userLocalService = userLocalService;
    }

    /**
     * Returns the user remote service.
     *
     * @return the user remote service
     */
    public com.liferay.portal.service.UserService getUserService() {
        return userService;
    }

    /**
     * Sets the user remote service.
     *
     * @param userService the user remote service
     */
    public void setUserService(
        com.liferay.portal.service.UserService userService) {
        this.userService = userService;
    }

    /**
     * Returns the user persistence.
     *
     * @return the user persistence
     */
    public UserPersistence getUserPersistence() {
        return userPersistence;
    }

    /**
     * Sets the user persistence.
     *
     * @param userPersistence the user persistence
     */
    public void setUserPersistence(UserPersistence userPersistence) {
        this.userPersistence = userPersistence;
    }

    /**
     * Returns the expando row local service.
     *
     * @return the expando row local service
     */
    public com.liferay.portlet.expando.service.ExpandoRowLocalService getExpandoRowLocalService() {
        return expandoRowLocalService;
    }

    /**
     * Sets the expando row local service.
     *
     * @param expandoRowLocalService the expando row local service
     */
    public void setExpandoRowLocalService(
        com.liferay.portlet.expando.service.ExpandoRowLocalService expandoRowLocalService) {
        this.expandoRowLocalService = expandoRowLocalService;
    }

    /**
     * Returns the expando row persistence.
     *
     * @return the expando row persistence
     */
    public ExpandoRowPersistence getExpandoRowPersistence() {
        return expandoRowPersistence;
    }

    /**
     * Sets the expando row persistence.
     *
     * @param expandoRowPersistence the expando row persistence
     */
    public void setExpandoRowPersistence(
        ExpandoRowPersistence expandoRowPersistence) {
        this.expandoRowPersistence = expandoRowPersistence;
    }

    /**
     * Returns the expando table local service.
     *
     * @return the expando table local service
     */
    public com.liferay.portlet.expando.service.ExpandoTableLocalService getExpandoTableLocalService() {
        return expandoTableLocalService;
    }

    /**
     * Sets the expando table local service.
     *
     * @param expandoTableLocalService the expando table local service
     */
    public void setExpandoTableLocalService(
        com.liferay.portlet.expando.service.ExpandoTableLocalService expandoTableLocalService) {
        this.expandoTableLocalService = expandoTableLocalService;
    }

    /**
     * Returns the expando table persistence.
     *
     * @return the expando table persistence
     */
    public ExpandoTablePersistence getExpandoTablePersistence() {
        return expandoTablePersistence;
    }

    /**
     * Sets the expando table persistence.
     *
     * @param expandoTablePersistence the expando table persistence
     */
    public void setExpandoTablePersistence(
        ExpandoTablePersistence expandoTablePersistence) {
        this.expandoTablePersistence = expandoTablePersistence;
    }

    /**
     * Returns the expando value local service.
     *
     * @return the expando value local service
     */
    public com.liferay.portlet.expando.service.ExpandoValueLocalService getExpandoValueLocalService() {
        return expandoValueLocalService;
    }

    /**
     * Sets the expando value local service.
     *
     * @param expandoValueLocalService the expando value local service
     */
    public void setExpandoValueLocalService(
        com.liferay.portlet.expando.service.ExpandoValueLocalService expandoValueLocalService) {
        this.expandoValueLocalService = expandoValueLocalService;
    }

    /**
     * Returns the expando value remote service.
     *
     * @return the expando value remote service
     */
    public com.liferay.portlet.expando.service.ExpandoValueService getExpandoValueService() {
        return expandoValueService;
    }

    /**
     * Sets the expando value remote service.
     *
     * @param expandoValueService the expando value remote service
     */
    public void setExpandoValueService(
        com.liferay.portlet.expando.service.ExpandoValueService expandoValueService) {
        this.expandoValueService = expandoValueService;
    }

    /**
     * Returns the expando value persistence.
     *
     * @return the expando value persistence
     */
    public ExpandoValuePersistence getExpandoValuePersistence() {
        return expandoValuePersistence;
    }

    /**
     * Sets the expando value persistence.
     *
     * @param expandoValuePersistence the expando value persistence
     */
    public void setExpandoValuePersistence(
        ExpandoValuePersistence expandoValuePersistence) {
        this.expandoValuePersistence = expandoValuePersistence;
    }

    public void afterPropertiesSet() {
        Class<?> clazz = getClass();

        _classLoader = clazz.getClassLoader();
    }

    public void destroy() {
    }

    /**
     * Returns the Spring bean ID for this bean.
     *
     * @return the Spring bean ID for this bean
     */
    @Override
    public String getBeanIdentifier() {
        return _beanIdentifier;
    }

    /**
     * Sets the Spring bean ID for this bean.
     *
     * @param beanIdentifier the Spring bean ID for this bean
     */
    @Override
    public void setBeanIdentifier(String beanIdentifier) {
        _beanIdentifier = beanIdentifier;
    }

    @Override
    public Object invokeMethod(String name, String[] parameterTypes,
        Object[] arguments) throws Throwable {
        Thread currentThread = Thread.currentThread();

        ClassLoader contextClassLoader = currentThread.getContextClassLoader();

        if (contextClassLoader != _classLoader) {
            currentThread.setContextClassLoader(_classLoader);
        }

        try {
            return _clpInvoker.invokeMethod(name, parameterTypes, arguments);
        } finally {
            if (contextClassLoader != _classLoader) {
                currentThread.setContextClassLoader(contextClassLoader);
            }
        }
    }

    protected Class<?> getModelClass() {
        return Book.class;
    }

    protected String getModelClassName() {
        return Book.class.getName();
    }

    /**
     * Performs an SQL query.
     *
     * @param sql the sql query
     */
    protected void runSQL(String sql) throws SystemException {
        try {
            DataSource dataSource = bookPersistence.getDataSource();

            SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(dataSource,
                    sql, new int[0]);

            sqlUpdate.update();
        } catch (Exception e) {
            throw new SystemException(e);
        }
    }
}
