create table tms_Customer (
	customerId LONG not null primary key,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	customerCode VARCHAR(75) null,
	customerName VARCHAR(75) null,
	inCharge VARCHAR(75) null,
	email VARCHAR(75) null,
	phone VARCHAR(75) null,
	address VARCHAR(75) null,
	parentId LONG
);

create table tms_Device (
	deviceId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	modelName VARCHAR(75) null,
	serialNumber VARCHAR(75) null,
	gponSerialNumber VARCHAR(75) null,
	boxSerialNumber VARCHAR(75) null,
	customerSerialNumber VARCHAR(75) null,
	manufacturerSerialNumber VARCHAR(75) null,
	hardwareRevision VARCHAR(75) null,
	softwareRevision VARCHAR(75) null,
	macAddress VARCHAR(75) null,
	partNumber VARCHAR(75) null,
	specification VARCHAR(75) null,
	factoryOut DATE null,
	purchaseOrderId LONG,
	warrantyFormId LONG,
	status INTEGER
);

create table tms_DeviceExt (
	deviceExtId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	modelName VARCHAR(75) null,
	serialNumber VARCHAR(75) null,
	gponSerialNumber VARCHAR(75) null,
	boxSerialNumber VARCHAR(75) null,
	customerSerialNumber VARCHAR(75) null,
	manufacturerSerialNumber VARCHAR(75) null,
	hardwareRevision VARCHAR(75) null,
	softwareRevision VARCHAR(75) null,
	macAddress VARCHAR(75) null,
	partNumber VARCHAR(75) null,
	specification VARCHAR(75) null,
	factoryOut DATE null,
	status INTEGER,
	ostStatusChangedDate DATE null,
	deviceExtOrderId LONG
);

create table tms_DeviceExtHis (
	deviceExtId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	modelName VARCHAR(75) null,
	serialNumber VARCHAR(75) null,
	gponSerialNumber VARCHAR(75) null,
	boxSerialNumber VARCHAR(75) null,
	customerSerialNumber VARCHAR(75) null,
	manufacturerSerialNumber VARCHAR(75) null,
	hardwareRevision VARCHAR(75) null,
	softwareRevision VARCHAR(75) null,
	macAddress VARCHAR(75) null,
	partNumber VARCHAR(75) null,
	specification VARCHAR(75) null,
	factoryOut DATE null,
	status INTEGER,
	ostStatusChangedDate DATE null,
	deviceExtOrderId LONG
);

create table tms_DeviceExtOrder (
	deviceExtOrderId LONG not null primary key,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	deviceExtOrderNumber VARCHAR(75) null,
	note VARCHAR(75) null
);

create table tms_DeviceHis (
	deviceId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	modelName VARCHAR(75) null,
	serialNumber VARCHAR(75) null,
	gponSerialNumber VARCHAR(75) null,
	boxSerialNumber VARCHAR(75) null,
	customerSerialNumber VARCHAR(75) null,
	manufacturerSerialNumber VARCHAR(75) null,
	hardwareRevision VARCHAR(75) null,
	softwareRevision VARCHAR(75) null,
	macAddress VARCHAR(75) null,
	partNumber VARCHAR(75) null,
	specification VARCHAR(75) null,
	factoryOut DATE null,
	purchaseOrderId LONG,
	warrantyFormId LONG,
	status INTEGER
);

create table tms_Partner (
	partnerId LONG not null primary key,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	partnerCode VARCHAR(75) null,
	partnerName VARCHAR(75) null,
	inCharge VARCHAR(75) null,
	email VARCHAR(75) null,
	phone VARCHAR(75) null,
	address VARCHAR(75) null
);

create table tms_PurchaseOrder (
	purchaseOrderId LONG not null primary key,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	customerId LONG,
	signDate DATE null,
	warrantyStartDate DATE null,
	warrantyEndDate DATE null,
	purchaseOrderNumber VARCHAR(75) null
);

create table tms_RmaReplacement (
	rmaRequestId LONG not null,
	replacedNumber VARCHAR(75) not null,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	status INTEGER,
	primary key (rmaRequestId, replacedNumber)
);

create table tms_RmaRequest (
	rmaRequestId LONG not null primary key,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	groupId LONG,
	rmaRequestNumber VARCHAR(75) null,
	customerId LONG,
	cusInCharge VARCHAR(75) null,
	cusEmail VARCHAR(75) null,
	cusPhone VARCHAR(75) null,
	cusAddress VARCHAR(75) null,
	creatingEstReturnDate DATE null,
	creatingAssignedDate DATE null,
	creatingNote VARCHAR(75) null,
	creatingImportedFileName VARCHAR(75) null,
	status INTEGER
);

create table tms_RmaRequestDevice (
	rmaRequestId LONG not null,
	deviceId LONG not null,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	originalSerialNumber VARCHAR(75) null,
	faultyDate DATE null,
	faultyNote VARCHAR(75) null,
	action VARCHAR(75) null,
	partnerId LONG,
	partnerInCharge VARCHAR(75) null,
	partnerEmail VARCHAR(75) null,
	partnerPhone VARCHAR(75) null,
	partnerAddress VARCHAR(75) null,
	sendingEstReturnDate DATE null,
	sendingReturnedDate DATE null,
	sendingAssignedDate DATE null,
	sendingNote VARCHAR(75) null,
	receivingReturnedDate DATE null,
	receivingNote VARCHAR(75) null,
	returningReturnedDate DATE null,
	returningNote VARCHAR(75) null,
	duplicatedRmaRequestId LONG,
	deniedDate DATE null,
	deniedNote VARCHAR(75) null,
	replacedDate DATE null,
	replacedNote VARCHAR(75) null,
	replacedNumber VARCHAR(75) null,
	replacedOldDeviceId LONG,
	replacedOldDeviceExtId LONG,
	replacedNewDeviceId LONG,
	replacedNewDeviceExtId LONG,
	oldStatus INTEGER,
	status INTEGER,
	statusByUserId LONG,
	statusDate DATE null,
	primary key (rmaRequestId, deviceId)
);

create table tms_WarrantyForm (
	warrantyFormId LONG not null primary key,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	agentCode VARCHAR(75) null,
	warrantyStartDate DATE null,
	warrantyEndDate DATE null,
	originalSerialNumber VARCHAR(75) null,
	hisSerialNumbers VARCHAR(75) null,
	latestSerialNumber VARCHAR(75) null,
	remark VARCHAR(75) null
);